FormidableLabs/victory

CONTRIBUTING.md, package.json, release-roadmap.md, src/components/victory.jsx, test/client/spec/components/victory.spec.jsx
cc/ @colinmegill 
I'm starting a guide for component consistency. It's mostly high level right now, but there are a small number of specific things that I think every component should have that are documented in a little more detail
=> add victory component style / ideology guide

components/app.jsx, components/theme.js
/cc @colin @lauren @david-davidson
=> Add copy to main/overview landing page

components/app.jsx
=> Add links to each victory component

docs/components/app.jsx, docs/components/theme.js, docs/settings.js
Let’s talk about copy! 
/cc @david-davidson @boygirl
=> Docs site: update copy

docs/components/app.jsx, docs/components/docs.jsx, docs/components/footer.jsx, docs/components/sidebar.jsx, docs/components/static-index.jsx, docs/components/static-render-entry.jsx, docs/components/theme.js, docs/ecology-getting-started.md, docs/ecology.md, docs/index.html, docs/router.jsx, docs/webpack.config.dev.js, docs/webpack.config.static.js, package.json
Merging this as soon as CI passes :+1: ; we can iterate from here.
=> Add `/docs` route and component playgrounds!

.travis.yml, DEVELOPMENT.md
=> Add note to use NPM v3

package.json
Fixes issue with NPM CDN.
Will publish `v0.1.1` with this.
=> Update to latest archetype

package.json
=> lock react router version

CONTRIBUTING.md
=> Add JSBin/JSFiddle to CONTRIBUTING.md

CONTRIBUTING.md
=> jsbin and jsfiddle point use latest victory

CONTRIBUTING.md
Hopefully this will lower the bar to entry.
cc @boygirl @knowbody
=> Add contribution guide!

CONTRIBUTING.md
- added note about builder (thanks @ryan-roemer).
- removed info about `dist` as we `.gitignore` it now
=> add builder note

docs/components/root.jsx, package.json
This is part of https://github.com/FormidableLabs/victory/issues/167, depends on releasing `builder-victory-component`.
=> Add <StyleRoot/> top-level component

demo/app.jsx, demo/demo.jsx, demo/index.html, package.json
Part of https://github.com/FormidableLabs/victory/issues/165.
=> Bug fix hot reloading

README.md
cc/ @coopy 
Please merge if this seems accurate.
=> add semver warning

.gitignore, .npmignore
Sorts the ignore files and adds `dist/*.map` to both `.npmignore` and `.gitignore`
=> Ignore src maps

package.json
Dependent on https://github.com/FormidableLabs/builder-victory-component/pull/36
=> Move url- and style-loader deps to archetype

docs/components/app.jsx, docs/components/static-index.jsx, docs/index.html
Resolves half of https://github.com/FormidableLabs/formidable.com/issues/177 
Add `<meta>` tag for SEO! Also changed a hard-coded color to a variable. 
/cc @elizagrace @boygirl @coopy
=> Docs: Add Meta description tag

README.md
"What to use Victory?" => "Want to use Victory?" :)
/cc @boygirl @ebrillhart
=> Quick typo fix in the README

README.md
=> lank workflow

CHANGELOG.md, package-lock.json, package.json
=> Update deps and changelog

packages/victory-area/package.json, packages/victory-axis/package.json, packages/victory-box-plot/package.json, packages/victory-brush-container/package.json, packages/victory-brush-line/package.json, packages/victory-candlestick/package.json, packages/victory-chart/package.json, packages/victory-core/package.json, packages/victory-create-container/package.json, packages/victory-cursor-container/package.json, packages/victory-errorbar/package.json, packages/victory-group/package.json, packages/victory-legend/package.json, packages/victory-line/package.json, packages/victory-pie/package.json, packages/victory-polar-axis/package.json, packages/victory-scatter/package.json, packages/victory-selection-container/package.json, packages/victory-shared-events/package.json, packages/victory-stack/package.json, packages/victory-tooltip/package.json, packages/victory-voronoi-container/package.json, packages/victory-voronoi/package.json, packages/victory-zoom-container/package.json, packages/victory/package.json
closes https://github.com/FormidableLabs/victory/issues/1060
=> add prop-types dep and improve package information

packages/victory-voronoi-container/src/voronoi-helpers.js
date values were causing NaNs for calculating voronoi layout.
=> coerce values to numbers when calculating voronoi positions

packages/victory-brush-container/src/brush-helpers.js, packages/victory-brush-container/src/victory-brush-container.js
Closes https://github.com/FormidableLabs/victory/issues/1073
=> add onBrushCleared prop for VictoryBrushContainer

packages/victory-tooltip/src/victory-tooltip.js
Fixes https://github.com/FormidableLabs/victory/issues/1017
Fixes https://github.com/FormidableLabs/victory/issues/947
=> change how tooltips are deactivated

packages/victory-legend/src/helper-methods.js, packages/victory-legend/src/victory-legend.js
Closes https://github.com/FormidableLabs/victory/issues/911
Renders title and border even when data is an empty array.
=> allow legends to render title annd border when data is an empty array

.travis.yml
https://docs.travis-ci.com/user/caching/#yarn-cache
=> Cache yarn packages on Travis to speed up builds

packages/victory-axis/src/helper-methods.js, packages/victory-core/src/victory-label/victory-label.js, packages/victory-core/src/victory-util/label-helpers.js, packages/victory-polar-axis/src/helper-methods.js
closes https://github.com/FormidableLabs/victory/issues/1083
=> audit for incorrect falsey checking breaking 0 angles

packages/victory-bar/src/bar.js, stories/victory-bar.js, yarn.lock
The barWidth function was not originally evaluating a function being passed in. 
Updated the `getBarWidth` function to evaluate the `barWidth` function to evaluate the function passed in with `datum` and `active` props.
=> Updated barWidth to evaluate width function with datum and active props.

packages/victory-axis/src/victory-axis.js
=> Added initialValue to reduce

packages/victory-bar/src/bar.js
=> Fix getCornerRadius typo, fixes #1181

packages/victory-core/src/victory-label/victory-label.js
=> Exposed `defaultStyles` as static property on `VictoryLabel`

packages/victory-core/src/victory-util/data.js, packages/victory-core/src/victory-util/wrapper.js
explicit group key rather than relying on eventKey for correctly grouping stacks
=> fix stacked group bug

packages/victory-chart/src/helper-methods.js, test/client/spec/victory-chart/helper-methods.spec.js
Allow multiple independent axes
=> don't filter independent axes

packages/victory-box-plot/src/victory-box-plot.js
fixes https://github.com/FormidableLabs/victory/issues/1260
=> use prop types shape instead of exact

packages/victory-core/src/victory-container/victory-container.js, test/client/spec/victory-area/victory-area.spec.js, test/client/spec/victory-axis/victory-axis.spec.js, test/client/spec/victory-bar/victory-bar.spec.js, test/client/spec/victory-box-plot/victory-box-plot.spec.js, test/client/spec/victory-candlestick/victory-candlestick.spec.js, test/client/spec/victory-chart/victory-chart.spec.js, test/client/spec/victory-errorbars/victory-errorbars.spec.js, test/client/spec/victory-group/victory-group.spec.js, test/client/spec/victory-line/victory-line.spec.js, test/client/spec/victory-pie/victory-pie.spec.js, test/client/spec/victory-scatter/victory-scatter.spec.js, test/client/spec/victory-stack/victory-stack.spec.js, test/client/spec/victory-voronoi/victory-voronoi.spec.js
tooltip alignment was off because the entire portal was vertically offset.
=> fix portal offset issue

packages/victory-core/src/victory-util/wrapper.js
fixes https://github.com/FormidableLabs/victory/issues/1303
=> rename private properties

package.json, packages/victory-area/package.json, packages/victory-axis/package.json, packages/victory-bar/package.json, packages/victory-box-plot/package.json, packages/victory-brush-container/package.json, packages/victory-brush-line/package.json, packages/victory-candlestick/package.json, packages/victory-chart/package.json, packages/victory-core/package.json, packages/victory-create-container/package.json, packages/victory-cursor-container/package.json, packages/victory-errorbar/package.json, packages/victory-group/package.json, packages/victory-legend/package.json, packages/victory-line/package.json, packages/victory-pie/package.json, packages/victory-polar-axis/package.json, packages/victory-scatter/package.json, packages/victory-selection-container/package.json, packages/victory-shared-events/package.json, packages/victory-stack/package.json, packages/victory-tooltip/package.json, packages/victory-voronoi-container/package.json, packages/victory-voronoi/package.json, packages/victory-zoom-container/package.json
fixes https://github.com/FormidableLabs/victory/issues/1340
=> ensure up to date lodash

packages/victory-pie/src/helper-methods.js
Fixes a minor bug affecting functional labels for `VictoryPie`
=> fix functional label bug

packages/victory-pie/src/helper-methods.js, stories/victory-pie.js
`padAngle` should be evaluated by `Slice`
=> fix functional padAngle prop

packages/victory-core/src/victory-container/victory-container.js
fixes a bug with user provided containerRef
=> use callback ref when provided by user

packages/victory-zoom-container/src/victory-zoom-container.js, yarn.lock
This re-fixes #622 by omitting `onWheel` when it's known to be noop
=> Fix scroll in <VictoryZoomContainer allowZoom={false} />

packages/victory-pie/src/helper-methods.js, packages/victory-pie/src/victory-pie.js, stories/victory-pie.js
This PR adds support for `labelPosition` as a function.
fixes https://github.com/FormidableLabs/victory/issues/1445
=> allow labelPosition as a function in VictoryPie

packages/victory-brush-container/src/brush-helpers.js
Closes https://github.com/FormidableLabs/victory/issues/1444
=> remove old check for svg target

demo/ts/app.tsx, demo/ts/components/victory-brush-line-demo.tsx, packages/victory-brush-line/src/index.d.ts, packages/victory-core/src/index.d.ts, packages/victory/src/index.d.ts
- Add typescript defs for Victory Brush Line
- Add typescript demo for Victory Brush Line
=> Add typescript prop defs and demo for VictoryBrush Line

packages/victory-bar/src/index.d.ts
Audited VictoryBar props and added "polar" to typescript prop defs
=> Add polar to VictoryBar props

demo/js/components/immutable-demo.js, demo/ts/app.tsx, demo/ts/components/immutable-demo.tsx, packages/victory-chart/src/index.d.ts, packages/victory-tooltip/src/index.d.ts
* Adds a typed `ImmutableDemo` 
* Updates type definition of the `events` prop for `VictoryChart`
* Updates type definition of the `style` prop for `VictoryTooltip`
=> Audits and adds demo: ImmutableDemo

packages/victory/src/index.d.ts, packages/victory/src/index.js
Adds export from `victory-histogram` added in #1531.
=> Add export of victory-histogram in victory

packages/victory/package.json
Adds a missing dependency on `victory-histogram`
=> Add missing victory-histogram dependency

.travis.yml
related to https://github.com/FormidableLabs/victory/issues/1567
=> disable chromatic until billing issues are resolved

CONTRIBUTING.md, packages/victory-core/src/victory-label/victory-label.js, test/client/spec/victory-axis/victory-axis.spec.js, test/client/spec/victory-core/victory-label/victory-label.spec.js
See https://github.com/FormidableLabs/victory/issues/1477
Docs change: https://github.com/FormidableLabs/victory-docs/pull/678
=> Allow the the customization of ID attr in VictoryLabel

packages/victory-voronoi-container/src/victory-voronoi-container.js
@NgoKnows 
This PR fixes the empty flyout bug you noticed
=> don't render empty flyouts

package.json, yarn.lock
Lerna @ ^3 handles package dev dependencies differently than ^2
=> downgrade lerna

package-scripts.js, packages/victory-area/README.md, packages/victory-axis/README.md, packages/victory-bar/README.md, packages/victory-box-plot/README.md, packages/victory-brush-container/README.md, packages/victory-brush-line/README.md, packages/victory-candlestick/README.md, packages/victory-chart/README.md, packages/victory-core/README.md, packages/victory-create-container/README.md, packages/victory-cursor-container/README.md, packages/victory-errorbar/README.md, packages/victory-group/README.md, packages/victory-legend/README.md, packages/victory-line/README.md, packages/victory-pie/README.md, packages/victory-polar-axis/README.md, packages/victory-scatter/README.md, packages/victory-selection-container/README.md, packages/victory-shared-events/README.md, packages/victory-stack/README.md, packages/victory-tooltip/README.md, packages/victory-voronoi-container/README.md, packages/victory-voronoi/README.md, packages/victory-zoom-container/README.md
change individual package readme links
=> update readmes with correct docs repo links

package.json, yarn.lock
fixes a bug that was preventing lerna for running karma checks correctly
=> update karma sauce launcher

packages/victory-core/src/victory-label/victory-label.js
=> provide missing props argument

packages/victory-core/src/victory-container/victory-container.js
fixes https://github.com/FormidableLabs/victory/issues/1656
=> fix ouiaSafe prop

packages/victory-core/src/victory-label/victory-label.js
This PR fixes an issue with background label heights I noticed while reviewing #1688
=> fix background label height adjustment

packages/victory-core/src/victory-label/victory-label.js, stories/victory-axis.stories.js
Fixes #1630 
This PR requires an update of Chromatic screenshots
=> Fix vertical alignment of axis labels

packages/victory-chart/src/helper-methods.js
Fixes https://github.com/FormidableLabs/victory/issues/1691
=> add key for chart background

docs/package.json, docs/src/content/docs/common-container-props.md, docs/src/content/docs/victory-container.md, docs/src/data/versions.js, docs/yarn.lock
Some docs updates for new props
=> update victory version and add new container props

packages/victory-core/src/index.d.ts, packages/victory-core/src/victory-label/victory-label.js, test/client/spec/victory-core/victory-label/victory-label.spec.js
This PR adds support for functions provided to the `angle` prop on `VictoryLabel`
=> support function angle prop for VictoryLabel

docs/src/content/docs/victory-tooltip.md, docs/src/content/guides/tooltips.md, docs/src/content/introduction/new.md, docs/src/data/versions.js
documents new tooltip behavior
=> document tooltip accessibility enhancement, update version data

packages/victory-core/src/victory-util/add-events.js
Fixes https://github.com/FormidableLabs/victory/issues/1719 
A regression was caused when caching logic was moved from `sCU` to `cDU` to fix bugs in react strict mode. This PR moves some of the caching logic back to `sCU`, leaving only calculated state change caching in `cDU`
=> cache all values except calculated state in sCU

docs/package.json, docs/src/content/docs/common-container-props.md, docs/src/data/versions.js, docs/yarn.lock
Docs update for the new `role` prop on `VictoryContainer`
=> document role prop for VictoryContainer and update version data

packages/victory-brush-container/src/brush-helpers.js, packages/victory-brush-container/src/victory-brush-container.js, packages/victory-core/src/victory-util/add-events.js, packages/victory-core/src/victory-util/events.js, packages/victory-shared-events/src/victory-shared-events.js
=> Free the mouse take 3

packages/victory-core/src/victory-primitives/background.js
Fixes https://github.com/FormidableLabs/victory/issues/1749
=> Add className prop to background component

packages/victory-tooltip/src/index.d.ts
Fixes https://github.com/FormidableLabs/victory/issues/1549
=> Add static defaultEvents to VictoryTooltip type

docs/src/content/docs/victory-zoom-container.md
Update clipContainerComponent example by removing unnecessary bracket.
=> Update clipContainerComponent example.

packages/victory-axis/src/helper-methods.js, packages/victory-axis/src/victory-axis.js, packages/victory-polar-axis/src/victory-polar-axis.js, test/client/spec/victory-axis/victory-axis.spec.js
fixes https://github.com/FormidableLabs/victory/issues/1779
=> remove unused type prop from axis primitives

packages/victory-shared-events/src/victory-shared-events.js
Done in response to this issue: https://github.com/FormidableLabs/victory/issues/1787
=> Issue 1787: Bind this during stringification of shared events cache values.

docs/package.json, docs/src/content/docs/victory-brush-container.md, docs/src/data/versions.js, docs/yarn.lock
A docs update for `VictoryBrushContainer`
=> update victory-brush-container docs for the latest version

.travis.yml, CONTRIBUTING.md, config/webpack/webpack.config.dev.js, packages/victory-core/package.json, yarn.lock
Fixes https://github.com/FormidableLabs/victory/issues/1818
@ryan-roemer thanks for the pointers!
=> no devtool config, no source maps

packages/victory/src/index.js
fixes https://github.com/FormidableLabs/victory/issues/1841
=> export victory-accessible-group from the main victory package

packages/victory-voronoi-container/package.json, yarn.lock
=> update delaunay find

packages/victory-chart/src/victory-chart.js, packages/victory-core/src/victory-util/hooks.js, packages/victory-group/src/victory-group.js, packages/victory-stack/src/victory-stack.js
This is the same refactor as #1937 and #1931 applied to VictoryChart. Once this gets merged to the feature branch, I will re-open a PR to main and run the Chromatic tests to make sure everything is working as expected!
=> Refactor VictoryChart

packages/victory-voronoi/package.json
=> remove dulicate yarn run

packages/victory-pie/src/victory-pie.js
Add array to PropTypes for events.eventKey in victory-pie
=> Fixes #1923

demo/js/components/canvas-demo.js, packages/victory-canvas/src/bar.js, packages/victory-canvas/src/curve.js, packages/victory-canvas/src/index.js, packages/victory-canvas/src/point.js, packages/victory/src/index.js, stories/canvas-bar.stories.js, stories/canvas-scatter.stories.js
This implements basic scatter and bar charts using canvas.
As of right now, these primitive components do not include:
+ Animations (I'm working on that)
+ Scatter point shapes other than circles
+ Polar bar charts (I think polar line charts work)
=> Adds canvas scatter and bar charts

packages/victory/src/index.d.ts
=> Uncomment type definitions for VictorySelectionContainer

packages/victory-core/src/index.d.ts
=> Add animationWhitelist to type definition

docs/src/content/faq/faq.md
=> add FAQ for Expo Web apps

demo/ts/components/group-demo.tsx, packages/victory-area/src/victory-area.js, packages/victory-bar/src/victory-bar.js, packages/victory-box-plot/src/victory-box-plot.js, packages/victory-candlestick/src/victory-candlestick.js, packages/victory-core/src/victory-util/add-events.js, packages/victory-errorbar/src/victory-errorbar.js, packages/victory-histogram/src/victory-histogram.js, packages/victory-line/src/victory-line.js, packages/victory-pie/src/victory-pie.js, packages/victory-scatter/src/victory-scatter.js, packages/victory-voronoi/src/victory-voronoi.js, test/client/spec/victory-area/victory-area.spec.js, test/client/spec/victory-bar/victory-bar.spec.js, test/client/spec/victory-box-plot/victory-box-plot.spec.js, test/client/spec/victory-candlestick/victory-candlestick.spec.js, test/client/spec/victory-errorbars/victory-errorbars.spec.js, test/client/spec/victory-histogram/victory-histogram.spec.js, test/client/spec/victory-line/victory-line.spec.js, test/client/spec/victory-pie/victory-pie.spec.js, test/client/spec/victory-scatter/victory-scatter.spec.js, test/client/spec/victory-voronoi/victory-voronoi.spec.js
Adds tests and logic to add safe user props to all top-level victory chart components.
=> Add safe user props to all top-level components

.gitignore, .yarnrc.yml, CONTRIBUTING.md, package.json
- Get rid of yarn2 files
- Add `engines` restriction
- Add CONTRBUTING notes.
=> Dev: Switch to ye olde yarn1

.gitignore, package.json
Just a tiny fix to prevent myself from making a dumb mistake again :)
=> Added helpful error message to 'test' script

test/jest/victory-histogram/victory-histogram.test.js
Part of the effort for #2195, this PR migrates all existing `victory-histogram` tests to Jest and RTL.
=> victory-histogram jest tests

package-scripts.js
=> Use build config for babel

packages/victory-chart/src/helper-methods.test.tsx, packages/victory-chart/src/victory-chart.test.tsx, packages/victory-chart/src/victory-chart.tsx, packages/victory-core/src/victory-util/collection.tsx, packages/victory-core/src/victory-util/hooks/use-animation-state.ts
This TS conversion helped me find the root cause of #2329.
This PR does nothing more than improve type-safety.
=> chore(typescript): improved type-safety of `use-animation-state`

packages/victory-core/src/index.ts
This fixes an issue with types throwing an error https://github.com/FormidableLabs/victory/issues/2355
=> Type export should not be with other exports

.changeset/shiny-emus-film.md, CONTRIBUTING.md, package.json
After closing the past few PRs, I realized I didn't add change logs for changesets to work. 
This PR includes multiple change logs for the past few PRs I've merged.
=> Recent changesets

packages/victory-core/src/victory-util/selection.ts
Remove cyclic dependency in victory-core / victory-util of `index.ts` -> `selection.ts` -> `index.ts`
=> Remove cyclic dependency

.github/workflows/chromatic.yml, .storybook/main.js, packages/victory-bar/src/v37/victory-bar.stories.tsx, packages/victory-line/src/v37/victory-line.stories.tsx
This reverts commit 8ac47935bf43009e9a3169108f22fa51c54b4ecb.
=> Enable Chromatic again

docs/src/partials/gallery/preview.js
Related to #2684 
[Preview](https://victory-5yx3g660g-formidable-labs.vercel.app/gallery) seems good.
=> Fix gallery page issues

docs/src/partials/sidebar/index.js
Fixes https://github.com/FormidableLabs/victory/issues/2686
Related to https://github.com/FormidableLabs/victory/pull/2685
=> Fix sidebar items not showing

packages/victory-line/src/victory-line.test.tsx
Migrate line test to typescript
=> Migrate line test to typescript

docs/package.json, docs/yarn.lock
Update docs site to victory@36.8.3
=> Update docs site to victory@36.8.3

.changeset/lucky-bikes-happen.md, packages/victory/package.json
Update victory package.json source to the correct index file
=> Update victory package.json source to the correct index file

docs/package.json, docs/yarn.lock
=> Update docs site to 36.8.5

docs/src/content/gallery/horizontal-stacked-bars.md
Add horizontal stacked bar chart gallery example
Closes #2798
=> Add horizontal stacked bar chart gallery example

demo/ts/app.tsx, demo/ts/index.html
Improve the demo app styling by adding a sidebar and some inoffensive styles.
=> Improve demo layout

.changeset/flat-phones-reply.md, packages/victory-core/src/exports.test.ts, packages/victory-core/src/victory-util/axis.tsx, packages/victory-core/src/victory-util/helpers.test.ts, packages/victory-core/src/victory-util/helpers.ts
Replace lodash invert with native code
=> Replace lodash.invert with native code

.changeset/giant-bulldogs-accept.md, packages/victory-legend/src/helper-methods.ts
Replace lodash sum with native code
=> Replace lodash.sum with native code

README.md
=> Update branding to nf in readme

CONTRIBUTING.md
Adding a note about using pnpm 7, as the lack of this information causes me to to encounter issues.
Documentation change
=> chore: Add note about pnpm version

website/docusaurus.config.ts
=> Fix for OG meta tags scheme

demo/ts/components/theme-builder/config-preview.tsx, demo/ts/components/theme-builder/index.tsx, demo/ts/components/theme-builder/options-config.tsx
This PR finishes adding all the basic controls (ones that don't require particularly new UI) for all chart types.
Tested on desktop chrome.
=> Feat: theme builder base options for all chart types

website/src/components/CalloutBanner.tsx, website/src/components/LearnMoreLink.tsx, website/src/components/SidebarLeadBanner.tsx, website/src/css/custom.css, website/src/pages/_components/landing-banner.tsx, website/src/pages/index.tsx, website/src/theme/DocItem/index.tsx, website/src/theme/DocSidebar/index.tsx
=> Lead capture banner

package.json, packages/victory-area/package.json, packages/victory-axis/package.json, packages/victory-bar/package.json, packages/victory-box-plot/package.json, packages/victory-brush-container/package.json, packages/victory-brush-line/package.json, packages/victory-candlestick/package.json, packages/victory-canvas/package.json, packages/victory-chart/package.json, packages/victory-core/package.json, packages/victory-create-container/package.json, packages/victory-cursor-container/package.json, packages/victory-errorbar/package.json, packages/victory-group/package.json, packages/victory-histogram/package.json, packages/victory-legend/package.json, packages/victory-line/package.json, packages/victory-pie/package.json, packages/victory-polar-axis/package.json, packages/victory-scatter/package.json, packages/victory-selection-container/package.json, packages/victory-shared-events/package.json, packages/victory-stack/package.json, packages/victory-tooltip/package.json, packages/victory-voronoi-container/package.json, packages/victory-voronoi/package.json, packages/victory-zoom-container/package.json, packages/victory/package.json, scripts/sync-pkgs-wireit-helpers.js
Set the node version to `>=18.0.0`. Vercel settings for this project are at 18, but we'd want to use 22 if available.
Fixes # (issue)
=> set engines node version
