components/app.jsx, components/docs.jsx, package.json, router.jsx
Adds google analytics route tagging to victory.
The manual `ga.pageview` calls are not ideal , but we can figure out a better way to do them in `react-router 1.0` later.
@david-davidson @paulathevalley
=> Docs google analytics

docs/components/theme.js
This is a quick fix as I am not sure where the scrollbars are coming from just yet...
/cc @david-davidson
=> Hide horizontal scrollbars on component playgrounds

docs/README.md
This somewhat meta PR adds docs for the docs site, in the form of `docs/README.md`. Covers overview, dev, deployment, gotchas. See anything missing?
/cc @boygirl @paulathevalley
=> Docs site: add documentation

docs/components/app.jsx, docs/components/docs.jsx, docs/components/theme.js
Resolves https://github.com/FormidableLabs/formidable-landers/issues/27 
- Fix sticky footer in Safari
- Remove duplicated `<Style>` tag 
- Find source of the horizontal scrollbars: the triple ticks notation wraps everything in `<pre>` tag, as per github flavored markdown rules, but this tag is the cause. For instance, if this tag was changed to `<div>` there would be no horizontal scrollbars, but I did not find a conventional way to add a class name to a `<div>` in markdown notation. 
/cc @david-davidson @boygirl
=> Docs: Fix a few style bugs

docs/webpack.config.static.js
I noticed that development warnings were showing up in the JS console at http://projects.formidablelabs.com/victory/:
Setting the `NODE_ENV` to production when building the static site takes care of this issue.
=> Disable React warnings when building static files for prod

package.json
[react-router 1.0.2](https://github.com/rackt/react-router/releases/tag/v1.0.2) requires `history` 1.13.x, but fresh installs are now getting 1.15.x, hence this `npm install` failure:
This just restricts us to 1.13.x. :+1: 
/cc @exogen @boygirl
=> Restrict `history` dep to 1.13.x

docs/components/app.jsx, docs/components/component-docs.jsx, docs/components/docs.jsx, docs/ecology-getting-started.md, docs/ecology.md
Here are a bunch of content tweaks:
* Adds a second `component-playground` on the homepage
* Adds "quick links" on the homepage: Gitter, GitHub, component-specific docs
* Swaps in new homepage subheads: "Friendly," "Flexible," "Composable"
* Adds  custom, Victory-specific header text
* Updates /docs entry point with normal code blocks instead of playgrounds, plus better getting-started explanation
* Implements a most-use-cases fix for the playground bug on the homepage: putting the closing JSX tags on the same line as the last props fixes it for every line except for the very last one (which is itself a closing tag: not something people will want to edit)
I'll add @exogen's  animation docs soon.
/cc @eastridge @boygirl
=> Content tweaks

README.md
This one's pretty straightforward: it just updates the links from the README. :+1: 
/cc @boygirl
=> [NO REVIEW] Link to up-to-date doc links from README

CONTRIBUTING.md
Does anybody know of a tool that generates a markdown code style document based on `.eslintrc`? Because that would be rad.
=> Add code style link to CONTRIBUTING.md

docs/webpack.config.dev.js
This will allow `npm link formidable-landers` to work for local testing without webpack choking on the symlink path. 
/cc @per @boygirl
=> Docs: Exclude the formidable-landers symlink for local testing

docs/components/app.jsx, docs/components/component-docs.jsx, docs/components/docs.jsx
Based on https://github.com/FormidableLabs/formidable-landers/pull/45
- Use default copy for header
- Set an explicit `backgroundColor` prop for the header and footer
- Set `maxWidth` for the props type column: 
/cc @coopy @david-davidson
=> Docs: Use default copy in header and set maxWidth to props table

docs/README.md, docs/components/app.jsx, docs/components/component-docs.jsx, docs/components/docs.jsx, docs/config.js, package.json
- Update header text in three places
- Override `display:flex` since that messes up the underline.
- Now the string lives in docs/config, for easier updates in the future.
- Add Roadmap link
- Update dev documentation for docs
=> Update header; Add Roadmap link

package.json
Fixes https://github.com/FormidableLabs/victory/issues/176
=> Add radium, lodash to devDeps; react to peerDeps

README.md, demo/demo.jsx, package.json
I've added standard npm scripts and updated the README to have the minimum needed to get started on development.
- `npm start` runs `builder run hot`
- `npm test` runs `builder run check`
I've also added primitives and composite components to demo app.
/cc @tptee @boygirl
=> Add `npm start` script and update README

.eslintrc, docs/index.html, package.json, test/.eslintrc
- We're removing the static-docs tasks from the archetype... https://github.com/FormidableLabs/builder-victory-component/pull/51
- ...so now those tasks live here.
- Also add `.eslintrc` files.
- ...and remove silly static `<script/>` includes from `docs/index.html`
=> Move static docs tasks to project; Upgrade archetype.

package.json
This makes victory's dependency on npm3 explicit:
```
npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your version of node/npm: victory@0.6.1
npm ERR! notsup Required: {"npm":">=3.0.0"}
npm ERR! notsup Actual:   {"npm":"2.14.16","node":"4.2.6"}
```
Rather than npm2 users having to find it out the long, large, slow way :smile: 
```
$ npm install victory
npm WARN optional dep failed, continuing fsevents@1.0.11
/ (for 276 MB of node_modules)
```
=> Prevent installation using npm2

src/index.js
Looks like there was a messy merge.  Victory won't build with a duplicate export.
=> remove duplicate VictoryAnimation

CHANGELOG.md, package.json, src/index.js, test/client/spec/components/victory.spec.js
**(VictoryVoronoiContainer)**
**BREAKING CHANGES**
- `VictoryTooltip` no longer automatically adds the `active` prop to data when hovered. To turn this behavior on, set the new `activateData` boolean prop on `VictoryTooltip`
- Deprecates `label` in favor of `labels` in `VictoryLine` and `VictoryArea`, allowing individual data labels for these components like in other Victory components. This will be a breaking change for anyone using the `label` prop in `VictoryLine` or `VictoryArea`. Series labels will need to be configured manually.
- `VictoryZoomContainer` now zooms both x and y dimensions, use the prop `dimension="x"` to return to the old behavior
- `VictoryZoomContainer` now centers zoom behavior on the mouse position rather than the center of the chart
- `VictoryZoomContainer` has a …
=> Update for 0.18.0 release

CHANGELOG.md, package.json, src/index.js, test/client/spec/components/victory.spec.js
- [victory-chart/469](https://github.com/FormidableLabs/victory-chart/pull/469) Adds `VictoryCursorContainer`
- [victory-core/241](https://github.com/FormidableLabs/victory-core/pull/241) Adds optional `title` an `desc` props to `VictoryLabel`
- [victory-core/243](https://github.com/FormidableLabs/victory-core/pull/243) Impovements to `VictoryContainer`
- Automatic `overflow: "visible"` for elements rendered in `VictoryPortal` (tooltips)
- `VictoryContainer` no longer renders `g` tags (this was causing confusion with evented containers)
- Default responsive styles are now `width: "100%"` `height: "100%"` (fixes a bug in safari)
- Changes the merge order for responsive styles so that `width` and `height` attrs may be overridden
- [victory-core/244](https://github.com/FormidableLabs/victory- …
=> update for release

README.md
I added a section to the README for dealing with this issue: https://github.com/FormidableLabs/victory/issues/613
=> Updates README to include instructions for dealing with non-deterministic clipIds in Jest snapshots.

.babelrc, .gitignore, .npmignore.publishr, package.json
This PR modernizes the Victory build and offerings. Generally:
- Provide an `es/` directory alongside `lib/` that has ES module export / imports (but everything else babel built) per the `redux` model. This model allows webpack2+ to use ESM resolution and enable tree-shaking, while is still backwards compatible with webpack1 which will use `lib/`
- Remove all references to `.jsx` since we don't use those anymore.
- Clean up and hone down a lot of stuff.
/cc @boygirl @chrisbolin
First, infrastructure:
* https://github.com/FormidableLabs/builder-victory-component-dev/pull/7
* https://github.com/FormidableLabs/builder-victory-component/pull/92
Second, core:
* https://github.com/FormidableLabs/victory-core/pull/266
Third, dependers:
* https://github.com/FormidableLabs/victory-pie/pull/149
* …
=> Webpack3 + ES6 Exports

CHANGELOG.md, demo/demo.js, package.json
**BREAKING CHANGES:**
**[victory-core/299](https://github.com/FormidableLabs/victory-core/pull/299) Containers are now rendered in parent divs.** This may be a breaking change for parent styles.
**[victory-chart/518](https://github.com/FormidableLabs/victory-chart/pull/518) Naming changes for container props**
`VictoryBrushContainer`
- `dimension` -> `brushDimension`
- `selectionComponent` -> `brushComponent`
- `selectedDomain` -> `brushDomain`
- `selectionStyle` -> `brushStyle`
- `onDomainChange` -> `onBrushDomainChange`
`VictoryCursorContainer`
- `dimension` -> `cursorDimension`
- `onChange` -> `onCursorChange`
`VictorySelectionContainer`
- `dimension` -> `selectionDimension`
`VictoryVoronoiContainer`
- `dimension` -> `voronoiDimension`
`VictoryZoomContainer`
- `dimension` -> …
=> update deps and changelog

config/webpack/webpack.config.test.js
`karma start ./config/karma/karma.conf.js` started failing with the following: 
```
==== JS stack trace =========================================
Security context: 0x261bcfc257c1 <JSObject>
1: /* anonymous */ [/Users/boygirl/formidable/v/victory/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:~342] [pc=0xf645ddea247](this=0x261b1100c211 <JSGlobal Object>,chunk=0x261b8c7b38b9 <String[33]\: /*! exports provided: default */\n>,original=0x261b6f771d19 <Object map = 0x261bd7ed1bf1>)
2: SourceNode_walk [/Users/boygirl/formidable/v/victory/node_modules/webp...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
...
```
removing `devtool: "source-map"` from `config/webpack/webpack.config.test.js` solves the issue. 
This is a temporary …
=> turn off source-maps for test

demo/components/debug-demo.js, packages/victory-zoom-container/src/victory-zoom-container.js
fixes https://github.com/FormidableLabs/victory/issues/1067
=> don't downsample stacked groups

packages/victory-brush-container/src/brush-helpers.js
The inconsistent behavior is a discrepancy in how the brush container handles redrawing the brush depending on the value of the allowResize prop if defaultArea is set to 'disable'  
Here's a quick demo: https://codesandbox.io/s/4jvl663pkw
This PR makes two changes, both small:
* fix a bug in a conditional check. I caught this by dumb luck, this bug is only surfaced if you defined brushDimension="x" and allowResize="false" on the brush container.
* added a check if the defaultBrushArea is defined and has area, for consistency with the behavior described in the [documentation](https://formidable.com/open-source/victory/docs/victory-brush-container/#defaultbrusharea)
I didn't add unit tests since there didn't seem to be any around the events for the brush helper. I feel bad submitting a PR …
=> fix inconsistent behavior with BrushContainer + minor bug

packages/victory-voronoi-container/src/victory-voronoi-container.js
Call the `labels` function in VictoryVoronoiContainer consistently with the same params (`point, index, points` as documented instead of `point, active` in `getStyle`).
=> Call labels with the appropriate params.

packages/victory-brush-container/src/victory-brush-container.js
This fixes VictoryBrushContainer should not show "rezise-cursor" when allowResize property is false, https://github.com/FormidableLabs/victory/issues/1095
=> Change cursor when allowResize and allowDrag are false

packages/victory-bar/src/bar.js
This PR fixes a bug where `cornerRadius` as a function was not being respected. This was corrected by replacing `isObject` with `isPlainObject`. This PR also simplifies the `getCornerRadius` method.
=> simplify cornerRadius method and fix functional cornerRadius

demo/components/victory-pie-demo.js, packages/victory-pie/README.md, packages/victory-pie/src/helper-methods.js, packages/victory-pie/src/victory-pie.js, stories/victory-pie.js
Added the option for "startAngle" and "endAngle" for the label to be
positioned.
The default is "centroid" which does not altere the original behavior.
As posted on the issue #1117 it would be nice to position the label
inside the actual slice but as per one rule of no-magic-numbers I can't
multiply by 0.9 to do this equally for all labels. This could be left
for later.
Closes #1117
=> Pie Label Positioning

packages/victory-brush-container/src/brush-helpers.js
My previous PR didn't account the drag and pan actions. Sorry about that.
=> Handle onBrushDomainChangeEnd on drag and pan of brush.

packages/victory-line/src/curve.js
@HalHaig This PR allows closed curves for cartesian charts.
polar charts will still default to closed interpolation, and cartesian charts will still default to open interpolations. To change this behavior:
```
<VictoryLine
dataComponent={<Curve openCurve={false} />}
...
/>
```
=> allow closed curves for cartesian charts

packages/victory-bar/src/bar.js, packages/victory-bar/src/helper-methods.js, packages/victory-bar/src/victory-bar.js, stories/victory-bar.js
- Add getPath prop to victory bar
- Add stories to storybook demonstrating usage
- For non-polar charts, getPath expects a function ({ x0, x1, y0, y1}) -> (string describing svg path)
- For polar charts, getPath expects a function ({ datum, start, end, r1, r2 }) -> (string describing svg path), where `datum`  is an object of shape {x, y},  `start/end` are angles derived from styles.width, and `r1/r2` are the radii (top/bottom) of each polar bar
=> Fix issue #1120

demo/components/external-events-demo.js, demo/components/victory-errorbar-demo.js, demo/components/victory-scatter-demo.js, packages/victory-pie/src/helper-methods.js, test/client/spec/svg-test-helper.js, test/client/spec/victory-bar/bar.spec.js, test/client/spec/victory-core/victory-primitives/point.spec.js, test/client/spec/victory-selection-container/selection-helpers.spec.js, test/client/spec/victory-shared-events/victory-shared-events.spec.js
This PR replaces all instances of `Object.assign` with lodash `assign`
fixes https://github.com/FormidableLabs/victory/issues/1142
=> audit and replace all instances of Object.assign with lodash assign

packages/victory-cursor-container/src/cursor-helpers.js
This is for a fix in victory-native.
Issue: https://github.com/FormidableLabs/victory-native/issues/349#issuecomment-430391540
Related PR in victory-native: https://github.com/FormidableLabs/victory-native/pull/394
=> Add onTouchEnd to the cursor-helpers to use in native cursor container

packages/victory-shared-events/src/victory-shared-events.js
This is no longer necessary after the addition of the concept of shared props in `Helpers.reduceChildren`, and was causing parent styles to incorrectly override child styles
=> don't need to clone child with parent props

.travis.yml, packages/victory-core/src/victory-util/domain.js
This PR corrects date checking when calculating domain from data, and fixes bugs related to single point time scale domains.
fixes https://github.com/FormidableLabs/victory/issues/1153
fixes https://github.com/FormidableLabs/victory-native/issues/410
=> correct date checking

yarn.lock
The offending `event-stream@3.3.6` was being included by one of our devDependencies, and made it into our `yarn.lock` before being unpublished. Victory users should not be affected.
=> update yarn.lock to remove vulnerable event-stream 

packages/victory-bar/README.md
=> docs(victory-bar): Typo fix

packages/victory-bar/src/helper-methods.js
fix(helper-method) getBaseProps incorrect handles when eventKey is 0 and loses the data.  Only fail over to the index if the eventKey is truly null or undefined.
Closes issue #1175
=> fix(bar): Bar chart is missing bar for the first value

packages/victory-core/src/victory-util/data.js, packages/victory-scatter/src/helper-methods.js, packages/victory-voronoi/src/helper-methods.js, test/client/spec/mock-components.js, test/client/spec/victory-core/victory-util/add-events.spec.js, test/client/spec/victory-core/victory-util/data.spec.js
I improved the performance of my charts with large datasets significantly by changing the `getEventKey` function in away that a new object is only created when `eventKey` is set in the `props`.
My reasoning for this change is:
1. If the datum has already an `eventKey` field, assign adds nothing.
2. If the index is used as fallback for `eventKey` the fallback can be (and already is in most cases) performed in the Components `getBaseProps`.
3. If the `eventKey` is computed the old behavior is required.
In my use case the perfomance of chart updates nearly doubled.
=> Improve performance for addEventKeys

demo/components/victory-area-demo.js, packages/victory-core/src/victory-util/domain.js, test/client/spec/victory-core/victory-util/domain.spec.js
Fixes #1123 
The `<VictoryArea />` and `<VictoryBar />` components rely on the `Domain.getDomainWithZero()` function to calculate their domain ranges. There was a regression introduced in version 0.27.0 where that function stopped respecting custom baseline domains via `data.y0` values and instead always set the minimum domain to 0.
=> Bugfix: Calculated domains respect custom baselines 

packages/victory-area/src/victory-area.js, packages/victory-axis/src/victory-axis.js, packages/victory-box-plot/src/victory-box-plot.js, packages/victory-core/src/victory-util/add-events.js, packages/victory-line/src/victory-line.js, packages/victory-polar-axis/src/victory-polar-axis.js
I couldn't find anything that calls the `getStateChanges()` method on the `addEvents` HOC, seems like it can be deleted?
=> Task: delete unused method on addEvents HOC

demo/components/events-demo.js, packages/victory-core/src/victory-util/helpers.js, packages/victory-core/src/victory-util/wrapper.js
@mxfr
I noticed a small regression causing parent events to use the incorrect eventKey. It was caused by the additional reduce in `reduceChildren` introduced in https://github.com/FormidableLabs/victory/pull/1211
I altered `reduceChildren` and moved the additional work into the custom `combine` method used when calculating the string map.
=> alter reduceChildren to fix parent events regression

demo/app.js, demo/components/animation-demo.js, demo/components/external-events-demo.js, demo/components/victory-area-demo.js, packages/victory-chart/src/victory-chart.js, packages/victory-core/src/victory-util/wrapper.js, packages/victory-group/src/victory-group.js, packages/victory-stack/src/victory-stack.js
Some odd behavior was happening when switching from `componentWillMount` to `componentDidMount`, so instead, `render` will set up events if they have not already been set up. This ensures that the first render has the correct events. Events are subsequently updated when props update.
=> remove componentWillMount

demo/components/performance.js, packages/victory-area/src/victory-area.js, packages/victory-axis/src/victory-axis.js, packages/victory-box-plot/src/victory-box-plot.js, packages/victory-chart/src/victory-chart.js, packages/victory-core/src/victory-animation/victory-animation.js, packages/victory-core/src/victory-transition/victory-transition.js, packages/victory-core/src/victory-util/add-events.js, packages/victory-core/src/victory-util/wrapper.js, packages/victory-group/package.json, packages/victory-group/src/victory-group.js, packages/victory-line/src/victory-line.js, packages/victory-polar-axis/src/victory-polar-axis.js, packages/victory-shared-events/package.json, packages/victory-shared-events/src/victory-shared-events.js, packages/victory-stack/package.json, packages/victory-stack/src/victory-stack.js
This PR uses `sCU` logic rather than `cWRP` for animating components
=> Remove componentWillReceiveProps

packages/victory-area/src/area.js
Fixes #1265 
I run `yarn nps test` and result was `Executed 650 of 651 (skipped 1) SUCCESS`. Not sure how to better test it.
=> fix area stroke on polar charts

packages/victory-legend/src/victory-legend.js
This PR fixes https://github.com/FormidableLabs/victory/issues/1291
=> Ensure VictoryLegend does not try to render a label for the dataKey "all"

packages/victory-box-plot/src/helper-methods.js, packages/victory-candlestick/src/candle.js, packages/victory-candlestick/src/helper-methods.js, packages/victory-candlestick/src/victory-candlestick.js, stories/victory-candlestick.js
Fixes: #1286 
Improvements on label support for `victory-candlestick`. This PR includes following label support for candlestick 
- lowLabels
- lowLabelComponent
- highLabels
- highLabelComponent
- openLabels
- openLabelComponent
- closeLabels
- closeLabelComponent
There is also continued support for `labels` and `labelComponent`.  `style` can be applied on all the different labels.
Also support `top`,` bottom`, `left`, `right` label orientation support for all the labels
TODO:
=> add diff labels and orientation support

packages/victory-core/src/victory-util/helpers.js, packages/victory-voronoi-container/package.json, packages/victory-voronoi-container/src/voronoi-helpers.js, yarn.lock
this PR reverts back to `d3-voronoi`, as the behavior for `delaunay` diagrams is different in undesirable ways for datasets with collinear points.
=> revert to d3-voronoi

demo/components/victory-voronoi-container-demo.js, packages/victory-core/src/victory-util/helpers.js, packages/victory-voronoi-container/package.json, packages/victory-voronoi-container/src/voronoi-helpers.js, yarn.lock
This PR replaces `d3-voronoi` with an improved version of `delaunay-find` which uses an updated version of the underlying `delaunator` package (which doesn't throw errors for degenerate datasets). The updated `delaunay-find` has tracked changes with `d3-delaunay`, but diverges in how it handles datasets with several collinear points. 
related: 
https://github.com/FormidableLabs/victory/issues/1341
https://github.com/FormidableLabs/delaunay-find/pull/8
=> use improved delaunay-find

packages/victory-voronoi-container/src/voronoi-helpers.js
This PR corrects a bug introduced when switching to `delaunay`. Prior to this fix, only the first matching point would be activated when mousing over a region that contained two identical points.
fixes https://github.com/FormidableLabs/victory/issues/1342
=> activate all matching points

package.json, packages/victory-area/package.json, packages/victory-axis/package.json, packages/victory-bar/package.json, packages/victory-box-plot/package.json, packages/victory-brush-container/package.json, packages/victory-brush-line/package.json, packages/victory-candlestick/package.json, packages/victory-chart/package.json, packages/victory-core/package.json, packages/victory-create-container/package.json, packages/victory-cursor-container/package.json, packages/victory-errorbar/package.json, packages/victory-group/package.json, packages/victory-legend/package.json, packages/victory-line/package.json, packages/victory-pie/package.json, packages/victory-polar-axis/package.json, packages/victory-scatter/package.json, packages/victory-selection-container/package.json, packages/victory-shared-events/package.json, packages/victory-stack/package.json, packages/victory-tooltip/package.json, packages/victory-voronoi-container/package.json, packages/victory-voronoi/package.json, packages/victory-zoom-container/package.json, yarn.lock
@boygirl This update is due to versions of lodash <= 4.17.11 being vulnerable to prototype pollution. 
https://www.npmjs.com/advisories/1065
=> chore(lodash): Update to version 4.17.15 (npm advisory 1065)

packages/victory-core/src/victory-container/victory-container.js, packages/victory-zoom-container/src/victory-zoom-container.js
This PR prevents the default wheel behavior on `VictoryContainer`'s outermost div when the events prop includes any `onWheel` events, as in `VictoryZoomContainer`. 
closes https://github.com/FormidableLabs/victory/issues/1272
=> fix scroll wheel interaction in chrome 

packages/victory-core/src/victory-container/victory-container.js
createContainer throws and error "can't get events of undefined - props.events"
=> fix error on createContainer with zoom and vonoroi

packages/victory-core/src/victory-animation/victory-animation.js
Spectacle transitions skip the last render causing incomplete effects and partially loaded slides. 
To reproduce it just inspect the DOM after the slide transitions and confirm that the final CSS _transform_ values such as _scale_ or _translate3d_ do not reach final values (i.e. scale=1 or translate3d=0).  
See https://codesandbox.io/s/simple-spectacle-example-e96d2 as an example. In this specific case, scale does not reach 1 but a number close to it such as 0.993772. In this case maybe it is not noticeable at a first look, but if the slide has many more components or the hardware is stressed, it could stop at lower values causing a very noticeable glitch in the layout.
Forcing the render on the terminating case should fix the issue.
Once this is fixed and released, Spectacle dependency …
=> Last frame of animation should not be skipped

packages/victory-axis/src/victory-axis.js, packages/victory-chart/src/helper-methods.js, packages/victory-chart/src/victory-chart.js, packages/victory-core/src/victory-primitives/circle.js, packages/victory-core/src/victory-primitives/line.js, packages/victory-core/src/victory-primitives/path.js, packages/victory-core/src/victory-primitives/rect.js, packages/victory-core/src/victory-primitives/text.js, packages/victory-core/src/victory-primitives/tspan.js, packages/victory-polar-axis/src/victory-polar-axis.js
- filter invisible / non-evented grid lines and ticks
- adds option to prepend default axes, which VictoryChart will use in native to prevent event blocking
- more consistent primitives
=> Improvements for native

packages/victory-area/src/area.js, packages/victory-area/src/victory-area.js, packages/victory-line/src/curve.js, packages/victory-line/src/victory-line.js, test/client/spec/svg-test-helper.js, test/client/spec/victory-area/victory-area.spec.js, test/client/spec/victory-line/victory-line.spec.js
This PR extends `interpolation` property in `VictoryLine` and `VictoryArea` by allowing to pass functions instead of interpolation names. This gives more control over curves from d3-shape (such as specifying [tension for cardinal curves](https://github.com/d3/d3-shape#curveCardinal_tension)) and also allows to use custom curves.
I think it fixes #561, though the proposed solution was different.
=> Accept custom interpolation functions

packages/victory-candlestick/src/helper-methods.js, stories/victory-candlestick.js
This PR corrects a bug that was occuring with automatic candle coloring for `VictoryCandlestick` when used with `open` and `close` data accessors.
=> correct automatic candlestick colors with data accessors

CONTRIBUTING.md
There was a third tilde missing in one of `CONTRIBUTING.md`'s code blocks, resulting in some improper formatting.  I've added it back in to correct that formatting issue.
=> Fix contributing document code block format

packages/victory-brush-container/src/brush-helpers.js
This PR fixes a bug where the incorrect domain was used in `onBrushEnd` callbacks. It also renames a couple variables and cleans up some code to make it clearer that a default domain is being used when the user clicks on the chart area without dragging.
Fixes #1400 
Related to https://github.com/FormidableLabs/victory/pull/1412
=> clear up logic around resetting to default domain

packages/victory-core/src/victory-util/textsize.js
This PR corrects the check for empty / nonexistent text in our text size approximation
Fixes https://github.com/FormidableLabs/victory/issues/1419
=> correct check for empty text

demo/components/victory-brush-container-demo.js, packages/victory-brush-container/src/brush-helpers.js, packages/victory-brush-container/src/victory-brush-container.js
This fixes #1432 by reusing `BrushHelpers.getHandles`
This also moves `brushDimension` checks to `BrushHelpers.getHandles`, to ensure that behaviour is consistent with cursors
=> Fix handles disappearing with `invertedAxis`

demo/components/victory-brush-container-demo.js, packages/victory-brush-container/src/brush-helpers.js, packages/victory-brush-container/src/victory-brush-container.js
I find it quite convenient to move the selected area without changing the zoom by just clicking at the desired location, like with scrollbars
=> Feature request: defaultBrushArea="move"

packages/victory-brush-container/src/brush-helpers.js, packages/victory-brush-container/src/victory-brush-container.js
When using `defaultBrushArea: 'move'`, it's too easy to accidentally draw a minimal selection when in fact you just click the empty area. I've added a customisable threshold for handling mouseMove with default of 2px
Probably related: https://github.com/FormidableLabs/victory/issues/1058
=> VictoryBrushContainer: add a threshold for mouseMove events to avoid accidental minimal draws

packages/victory-core/src/victory-util/data.js
Avoids expensive `stringMap` computation when using preformattedData. This improves the performance noticeably when using large datasets.
=> Slightly improve performance when using preformatted data.

packages/victory-core/src/victory-util/textsize.js
When using the `flyoutComponent` prop, and letting the rendered
component render any blank text, the `text` prop comes through as
`null`. This means that we try to stringify null.
This is a followup to #1425 which added this check in case the height
was the number value 0, but broke `null`.
Specifically, our code looks like:
```tsx
<VictoryBar
labelComponent={
<VictoryTooltip
renderInPortal={false}
dx={horizontal ? this.centerY(key) : 0}
dy={horizontal ? 0 : BAR_TOOLTIP_DISTANCE}
flyoutComponent={
<BarChartTooltip
position={Position.TOP}
getDatumLabel={this.formatDatum}
seriesKey={key}
/>
}
/>
}
...
```
Note that I also tried adding an explicit `text={undefined}` and `text=""` to trigger the existing null/etc but that ended up overriding the flyoutComponent prop.
=> Handle tooltip text when using custom flyoutComponent

demo/components/victory-voronoi-container-demo.js, packages/victory-tooltip/src/victory-tooltip.js, packages/victory-voronoi-container/src/victory-voronoi-container.js
Also add a demo to show what it enables
Fixes https://github.com/FormidableLabs/victory/issues/1473
Notes: I've added a demo, not a story, because there's a comment in stories stating "only add visual test for containers that have visual elements without interaction" which isn't the case here (interactions are needed to trigger tooltip)
=> Add activePoints props to flyout & label components in voronoi container

LICENSE.txt, packages/victory-area/src/index.d.ts, packages/victory-axis/src/index.d.ts, packages/victory-bar/src/index.d.ts, packages/victory-box-plot/src/index.d.ts, packages/victory-brush-container/src/index.d.ts, packages/victory-chart/src/index.d.ts, packages/victory-core/src/index.d.ts, packages/victory-create-container/src/index.d.ts, packages/victory-cursor-container/src/index.d.ts, packages/victory-group/src/index.d.ts, packages/victory-legend/src/index.d.ts, packages/victory-line/src/index.d.ts, packages/victory-pie/src/index.d.ts, packages/victory-scatter/src/index.d.ts, packages/victory-stack/src/index.d.ts, packages/victory-tooltip/src/index.d.ts, packages/victory-voronoi-container/src/index.d.ts, packages/victory-zoom-container/src/index.d.ts, packages/victory/src/index.d.ts
This PR imports the latest typescript definitions from definitely typed!  It's set to merge into a feature branch (`feature/typescript-defs`) so we can work out any kinks/typos before pushing to master.  This is the first of a few PRs.
**Upcoming PRs will add the following**
- Lint support for our typescript files.
- Demo project written in typescript.
- More type definitions (definitely typed did _not_ cover all packages)
**NOTE:**  If you take a look at the `index.d.ts` file in the main `victory` folder, you'll notice a lot of lines commented out.  Each import/export line commented out is an item that still needs type defs in order to fully cover the entire list of victory features.
=> Imported typescript definitions from definitely typed

packages/victory-brush-container/package.json
As per this [case study](https://github.com/yarnpkg/berry/issues/843), victory-brush-container is missing a reference to `react-fast-compare`
=> fix: Missing package.json dep - react-fast-compare

package-scripts.js, packages/victory-chart/src/index.d.ts, packages/victory-core/src/index.d.ts, tsconfig.json
This PR fixes a small bug I found in the typescript definitions that wasn't caught by `eslint`.  
After some googling, I realized that `typescript-eslint` does not catch very specific typescript errors (like interface errors, or type mis-match errors).  So the best way to ensure that all the typescript code (and definition files) are correct is to use `tsc` to compile the typescript files in the project. `tsc` will catch any type errors that `typescript-eslint` misses.
So, I added `lint.ts` to our linting pipeline.  It will simply build the typescript files (with no output generated thanks to the `noEmit` flag) and report any build errors.  This caught the bug in our definitions, so I was able to fix it and re-lint and voila things are working!
**Note:** The bug was that …
=> Fixed typescript props bug and added typescript compile to linting process

packages/victory-legend/src/index.d.ts
Hi!
As seen in the [documentation for VictoryLegend](https://formidable.com/open-source/victory/docs/victory-legend/#style), a VictoryLegend style prop can expect styling for the `title` property. However, when we look at the type definition for `VictoryLegendProps`, we see that the style property uses `VictoryStyleInterface`, which does not contain a property for `title`.
This PR simply combines the optional `title` style property with `VictoryStyleInterface` to fulfill this definition. `title` is a `VictoryStyleObject` identical to the other properties in the interface.
=> Fix VictoryLegendProps style typing by adding title property

packages/victory-brush-line/package.json, packages/victory-group/package.json, packages/victory-stack/package.json, packages/victory-voronoi-container/package.json
Closes #1495
Victory charts is incompatible with Yarn PnP due to out of spec imports.
For example, `victory-voronoi-container` imports `react-fast-compare` but it is not declared in `victory-voronoi-container`s package.json.
This currently works for other package managers due to how the node_modules folders just happen to be mounted, but this should be considered undefined behavior.
This PR adds the imported dependencies into the relevant package.json files.
=> Added missing dependencies

demo/js/components/victory-brush-container-demo.js, demo/ts/app.tsx, demo/ts/components/victory-brush-container-demo.tsx, packages/victory-brush-container/src/index.d.ts, packages/victory-zoom-container/src/index.d.ts
* Adds a `VictoryBrushContainerDemo` 
* Updates some of the mislabelled props for the demos
* Updates the type definition to use `RangeTuple` instead of `DomainPropType` since it is possible to have the prop to not be provided initially, therefore `DomainPropType` is the wrong type definition due to it requiring either `x` or `y`
* Adds additional missing props for `VictoryBrushContainerProps` interface
=> Add types and demo: VictoryBrushContainer

demo/ts/app.tsx, demo/ts/components/victory-shared-events-demo.tsx, packages/victory-area/src/index.d.ts, packages/victory-bar/src/index.d.ts, packages/victory-candlestick/src/index.d.ts, packages/victory-core/src/index.d.ts, packages/victory-group/src/index.d.ts, packages/victory-legend/src/index.d.ts, packages/victory-line/src/index.d.ts, packages/victory-pie/src/index.d.ts, packages/victory-polar-axis/src/index.d.ts, packages/victory-scatter/src/index.d.ts, packages/victory-shared-events/src/index.d.ts, packages/victory-stack/src/index.d.ts, packages/victory-voronoi/src/index.d.ts
This PR introduces types for `VictorySharedEvents` and updates our spelling of `Labelable` across 3 different interfaces.
Tested by running `yarn nps check.dev` locally
=> Add types: VictorySharedEvents

LICENSE.txt, packages/victory-area/src/index.d.ts, packages/victory-axis/src/index.d.ts, packages/victory-bar/src/index.d.ts, packages/victory-box-plot/src/index.d.ts, packages/victory-brush-container/src/index.d.ts, packages/victory-brush-line/src/index.d.ts, packages/victory-candlestick/src/index.d.ts, packages/victory-chart/src/index.d.ts, packages/victory-core/src/index.d.ts, packages/victory-create-container/src/index.d.ts, packages/victory-cursor-container/src/index.d.ts, packages/victory-group/src/index.d.ts, packages/victory-legend/src/index.d.ts, packages/victory-line/src/index.d.ts, packages/victory-pie/src/index.d.ts, packages/victory-scatter/src/index.d.ts, packages/victory-stack/src/index.d.ts, packages/victory-tooltip/src/index.d.ts, packages/victory-voronoi-container/src/index.d.ts, packages/victory-voronoi/src/index.d.ts, packages/victory-zoom-container/src/index.d.ts
Open for discussion, but this seems like a nice and simple way to credit our early DefinitelyTyped contributors while also cleaning up the indices for future contributions.
=> Move DefinitelyTyped credits to the License

demo/ts/app.tsx, demo/ts/components/victory-cursor-container-demo.tsx, packages/victory-cursor-container/src/index.d.ts
- Enforce number from cursorLabel function
- Added VictoryCursorContainer demo
=> Audit typescript props and add a demo for VictoryCursorContainer

packages/victory-stack/src/index.d.ts
Add the following props to VictoryStack:
- children
- fillInMissingData
- origin
and remove the following redundant props:
- domainPadding
- horizontal
=> Update DefinitelyTyped props for VictoryStack

demo/ts/app.tsx, demo/ts/components/victory-selection-container-demo.tsx, packages/victory-core/src/index.d.ts, packages/victory-selection-container/src/index.d.ts
This PR
- enhances the shared VictoryContainerProps
- adds types for the VictorySelectionContainer
- adds a tsx demo to test the VictorySelectionContainer types
=> Add types: VictorySelectionContainer

packages/victory-pie/src/index.d.ts
Add the following props:
VictorySlice:
- innerRadius
VictoryPie:
- categories
- cornerRadius
- innerRadius
- labelPosition
- labelRadius
- origin
- padAngle
- radius
=> Add missing DefinitelyTyped props to VictorySlice and VictoryPie

packages/victory-voronoi/src/index.d.ts
This PR adds typescript DefinitelyTyped prop definitions for the Voronoi Primitive Component, which I missed when adding Voronoi
=> Add Voronoi primitive component DefinitelyTyped props

demo/ts/app.tsx, demo/ts/components/victory-errorbar-demo.tsx, packages/victory-area/src/index.d.ts, packages/victory-candlestick/src/index.d.ts, packages/victory-core/src/index.d.ts, packages/victory-errorbar/src/index.d.ts, packages/victory-line/src/index.d.ts, packages/victory-polar-axis/src/index.d.ts, packages/victory-scatter/src/index.d.ts, packages/victory-stack/src/index.d.ts, packages/victory-tooltip/src/index.d.ts
Still need to resolve various issues with the styles in the demo
=> [WIP] Add types: VictoryErrorBar

demo/js/components/victory-zoom-container-demo.js, demo/ts/app.tsx, demo/ts/components/victory-brush-container-demo.tsx, demo/ts/components/victory-cursor-container-demo.tsx, demo/ts/components/victory-zoom-container-demo.tsx, packages/victory-brush-container/src/index.d.ts, packages/victory-core/src/index.d.ts, packages/victory-cursor-container/src/index.d.ts, packages/victory-zoom-container/src/index.d.ts
* Updates the name of `CursorData` to `CoordinatesPropType` 
* Updates the `VictoryBrushContainerProps` and `VictoryBrushContainerDemo` to use `DomainTuple` instead `RangeTuple`
* Adds a `VictoryZoomContainerDemo`
* Adds and updates missing props and their typescript definitions for `VictoryZoomContainerProps` interface
* Removes props from `VictoryZoomContainerProps` interface that do not belong
=> Audits and Adds typescript props, definitions, and demo: VictoryZoomContainer

demo/js/components/selection-demo.js, demo/ts/app.tsx, demo/ts/components/selection-demo.tsx
* Adds a typescript `SelectionDemo`
* Removes `size` prop from the `VictoryBar` in `SelectionDemo` since `VictoryBar` does not take a `size` prop
=> Audits and adds demo: SelectionDemo

demo/ts/app.tsx, demo/ts/components/draggable-demo.tsx, demo/ts/components/victory-brush-container-demo.tsx, packages/victory-brush-container/src/index.d.ts, packages/victory-brush-line/src/index.d.ts, packages/victory-core/src/index.d.ts, packages/victory-zoom-container/src/index.d.ts, packages/victory/src/index.d.ts
This PR:
- Adds the draggable demo
- Replaces object literals with DomainPropType where appropriate
=> Add draggable demo, make sure DomainPropType is used where approriate

packages/victory-core/src/index.d.ts, packages/victory/src/index.d.ts
This PR adds an interface for TextSizeStyle and exports types for public TextSize methods
=> Export TextSize types from VictoryCore

demo/js/components/victory-voronoi-container-demo.js, demo/ts/app.tsx, demo/ts/components/victory-voronoi-container-demo.tsx, packages/victory-chart/src/index.d.ts, packages/victory-stack/src/index.d.ts, packages/victory-tooltip/src/index.d.ts
* Adds a typed `VictoryVoronoiContainerDemo`
* Updates and fixes props data for `VictoryVoronoiContainerDemo`
* Removes unused imports of `DomainPaddingPropType` from `VictoryChart` and `VictoryStack`
=> Audits and adds demo: VictoryVoronoiContainerDemo

packages/victory-bar/src/helper-methods.js, packages/victory-group/src/helper-methods.js, packages/victory-stack/src/helper-methods.js
A regression was introduced in `34.1.3` when a check was added for `props.domain`. This PR corrects the regression by individually checking for domain props for each dimension.
Fixes https://github.com/FormidableLabs/victory/issues/1562
=> per dimension domain prop checking

demo/js/components/victory-axis-demo.js, demo/js/components/victory-chart-demo.js, demo/ts/components/victory-chart-demo.tsx, demo/ts/components/victory-polar-axis-demo.tsx, packages/victory-chart/src/helper-methods.js, packages/victory-chart/src/index.d.ts, packages/victory-chart/src/victory-chart.js, packages/victory-core/src/index.d.ts, packages/victory-core/src/index.js, packages/victory-core/src/victory-primitives/background.js, packages/victory/src/index.d.ts, packages/victory/src/index.js, stories/victory-chart.js
* Adds a new `Background` primitive component
* Adds the background primitive to `VictoryChart` to allow an option for adding background for just the chart area
* Updates typed definitions for `VictoryChartProps` interface
* Updates the helper-methods in `VictoryChart` to accept a `background` prop
* Adds additional stories to `VictoryChart` storybook to visually check that the background color is rendered correctly
=> VictoryChart: adds an option for adding background for chart area

packages/victory-chart/src/index.d.ts
Adds the missing `backgroundComponent` prop to `VictoryChartProps` interface #1558
=> Adds backgroundComponent prop to VictoryChartProps interface

packages/victory-histogram/package.json
https://github.com/FormidableLabs/victory/blob/master/packages/victory-histogram/src/helper-methods.js
Requires both `d3-scale` and `react-fast-compare` without including them in the package.json.
This works by coincidence in some codebases but will fail in any using Yarn v2.
This has happened a couple of times before:
https://github.com/FormidableLabs/victory/pull/1478
https://github.com/FormidableLabs/victory/pull/1496
https://github.com/FormidableLabs/victory/pull/1570
I would recommend adding a test to your CI that installs and runs some tests of the package using Yarn v2 to catch these errors before release, given these patch / minor changes break downstream dependencies.
=> Add missing dependencies in victory-histogram

.travis.yml, demo/js/components/victory-histogram-demo.js, demo/ts/components/victory-histogram-demo.tsx, packages/victory-bar/src/bar.js, packages/victory-bar/src/helper-methods.js, packages/victory-bar/src/path-helper-methods.js, packages/victory-core/src/victory-util/label-helpers.js, packages/victory-histogram/src/helper-methods.js
This fixes an issue that was occurring where tooltips being rendered by `VictoryVoronoiContainer`  for `VictoryHistogram` were being placed at the beginning of the bin (`x0`), which leads to a slightly weird positioning. To fix that, the middle of the bin is now used, so this should lead to a more intuitive positioning.
=> Fix Histogram Tooltip Positioning

packages/victory-shared-events/src/victory-shared-events.js
This PR implements caching the `sharedEvents` prop created by `victory-shared-events` to prevent re-renders, which improves the performance of Victory container components.
**TL;DR**
`VictoryCursorContainer` - significant performance increase
`VictorySelectionContainer` - significant performance increase
`VictoryBrushContainer` - significant performance increase in _uncontrolled_ cases (ie doesn't re-render on each mousemove)
`VictoryVoronoiContainer` - small - medium performance increase, with more sparsely positioned data getting more of a performance increase
`VictoryZoomContainer` -  should have a small increase due to not re-rendering axes in _uncontrolled_ cases
- **GIFs are _after_ changes**
- **Measurements were made in production mode**
=> Cache sharedEvents prop to prevent re-renders

packages/victory-cursor-container/src/cursor-helpers.js, packages/victory-cursor-container/src/victory-cursor-container.js
This fixes #1276, where the cursor wasn't disappearing after your mouse leaves `VictoryCursorContainer`.
This issue can be reproduced by putting your mouse inside a `VictoryCursorContainer` and then quickly moving it outside the container.
=> Fix cursor not disappearing on mouse leave

packages/victory-group/src/helper-methods.js, stories/victory-bar.js
This PR is a fix for stacked groups based on work in  https://github.com/FormidableLabs/victory/pull/1602
A story is also added to cover this case to guard against future regressions.
fixes #1315
=> fix offset for stacked groups

packages/victory-chart/src/helper-methods.js, stories/victory-chart.js
Found bug with paddings when axis "orientation" prop is set.
The trick is to take padding for axis depend on "orientation" prop if it is set. Also add story for reproduction and check.
=> Fix axes paddings for different orientation options

demo/ts/components/victory-zoom-container-demo.tsx, packages/victory-core/src/index.d.ts
Adds a missing type to container props. Fix issue found here https://spectrum.chat/victory/general/how-do-i-use-the-containerref-prop~03f68b9e-6b08-4b5b-acd3-2d1a8b823ec0
=> Add missing type for containerRef

demo/js/components/victory-voronoi-container-demo.js, demo/ts/components/victory-voronoi-container-demo.tsx, packages/victory-voronoi-container/src/index.d.ts, packages/victory-voronoi-container/src/victory-voronoi-container.js, packages/victory-voronoi-container/src/voronoi-helpers.js
Instead of the `voronoiPadding` reducing voronoi trigger events via the same amount on every side, it can now behave more like the `padding` prop. This change allows a chart to have different `voronoiPadding` for the bottom, left, right, and top areas.
See https://github.com/FormidableLabs/victory/issues/1619
=> voronoiPadding type to accept PaddingProps

packages/victory-core/src/index.d.ts
The typing is incorrect for the approximateTextSize utility function. This PR corrects the return shape to be `{width:number, height:number}`.
Also, based on the code and tests for the function, it appears that calling without the second style object is allowed so I marked it optional.
=> Approximate text size typing fix

.gitignore, demo/js/app.js, demo/js/components/ouia-demo.js, demo/ts/app.tsx, demo/ts/components/ouia-demo.tsx, docs/src/content/docs/common-container-props.md, packages/victory-core/src/index.d.ts, packages/victory-core/src/victory-container/victory-container.js
In order to better support automated testing, we would like to add the properties below to the root HTML element output by `VictoryContainer`.
These properties are defined by the Open UI Automation (OUIA) 1.0-RC spec.
https://ouia.readthedocs.io/en/latest/README.html#ouia-component
```
data-ouia-component-type
data-ouia-component-id
data-ouia-safe
```
Fixes https://github.com/FormidableLabs/victory/issues/1624
=> Add OUIA props to VictoryContainer

docs/src/content/docs/victory-axis.md
`LinSegmente` => `LineSegment`
This is a copy of #1662 opened by a core contributor so that CI will trigger a new docs deployment 
Thanks @khjrtbrg for this fix!
=> docs(victory-axis): Typo fix

packages/victory-core/src/index.d.ts, packages/victory-core/src/victory-container/victory-container.js, stories/victory-container.stories.js, test/client/spec/victory-area/victory-area.spec.js, test/client/spec/victory-axis/victory-axis.spec.js, test/client/spec/victory-bar/victory-bar.spec.js, test/client/spec/victory-box-plot/victory-box-plot.spec.js, test/client/spec/victory-candlestick/victory-candlestick.spec.js, test/client/spec/victory-chart/victory-chart.spec.js, test/client/spec/victory-errorbars/victory-errorbars.spec.js, test/client/spec/victory-group/victory-group.spec.js, test/client/spec/victory-histogram/victory-histogram.spec.js, test/client/spec/victory-line/victory-line.spec.js, test/client/spec/victory-pie/victory-pie.spec.js, test/client/spec/victory-scatter/victory-scatter.spec.js, test/client/spec/victory-stack/victory-stack.spec.js, test/client/spec/victory-voronoi/victory-voronoi.spec.js
This PR switches to `height: "100%"` from `height: "auto"` on `VictoryContainer`'s outermost div, and adds support for a `preserveAspectRatio` prop that can be added to `VictoryContainer` to give users more control over how the chart fills its container:
closes https://github.com/FormidableLabs/victory/issues/1684
=> add `preserveAspectRatio` prop

packages/victory-core/src/index.d.ts, packages/victory-core/src/victory-container/victory-container.js, test/client/spec/victory-core/victory-container/victory-container.spec.js
Added aria-labelledby and aria-describedby props to the VictoryContainer
component. Unlike the existing title and desc props which accept strings,
these props accept ids so that the container can be labelled by other
elements in the DOM. This is especially important when the container may
be labelled or described by complex markup (e.g. labelled by a link or described by a table) instead of
something that can be easily reduced to a plain string.
A demo page might be a good idea, but I don't want to conflict with #1687. Maybe we add some container aria attributes to that when both of these are merged?
=> Add aria attributes to VictoryContainer

demo/js/app.js, demo/js/components/accessibility-demo.js, demo/ts/app.tsx, demo/ts/components/accessibility-demo.tsx, packages/victory-bar/src/bar.js, packages/victory-bar/src/helper-methods.js, packages/victory-bar/src/index.d.ts, packages/victory-core/src/index.d.ts, packages/victory-core/src/victory-util/common-props.js, test/client/spec/victory-bar/victory-bar.spec.js
This PR adds the following props to the `VictoryBar` component:
`ariaLabel`: string or callback
`tabindex`: number or callback
Bars can now be tabbed individually with a unique aria-label applied to each (using the props available in the `CallbackArgs`:
```
export interface CallbackArgs {
active: boolean;
datum: any;
horizontal: boolean;
index: number;
x: number;
y: number;
scale?: {
x?: D3Scale;
y?: D3Scale;
};
}
``` 
This new feature is demo-able by running this branch, visiting localhost:3000 and clicking the new AccessibilityDemo link (both ts and standard js)
From there you can click anywhere on the bar graph space, hit tab, and you should see the focus move from one bar to the next. Inspecting the elements via devtools should show the aria-labels on each path component.
Todo: 
I …
=> Feature/VictoryBar & Bar components ariaLabel and tabIndex [ready]

docs/src/content/common-props/common-props.md
Changed "be these may be modified" to "but these may be modified" in common-props docs page.
=> Corrected  typo in common-props docs

demo/js/components/victory-voronoi-container-demo.js, packages/victory-voronoi-container/src/victory-voronoi-container.js
This PR corrects a bug that was causing `VictoryVoronoiContainer` to override the `text` prop provided directly to `VictoryTooltip`. 
Closes https://github.com/FormidableLabs/victory/issues/1681
Also respects `style`, `flyoutStyle`, `width` and `height` when they are given as explicit props on `VictoryTooltip`
=> Don't override all tooltip props in VictoryVoronoiContainer

demo/js/components/victory-tooltip-demo.js, packages/victory-tooltip/src/victory-tooltip.js
This PR adds `onFocus` and `onBlur` event handlers for `VictoryTooltip` to enable showing tooltips when users tab through rather than mouse over a chart. This work goes along with the recent addition of `tabIndex` to all primitive components.
=> add onFocus and onBlur events for VictoryTooltip

packages/victory-core/src/victory-label/victory-label.js
Closes https://github.com/FormidableLabs/victory/issues/1679
For labels that use `datum` rather than x, y coordinate positioning, calculate x, y coordinates before calculating transform.
=> find datum coordinates before transform

packages/victory-core/src/victory-util/events.js
Issue: Victory codebase uses `return {}` as a way of saying "ignore this event", but it still leads to rerendering of `VictorySharedEvents` and therefore its children
=> Avoid rerenders on ignored events

packages/victory-cursor-container/src/cursor-helpers.js
Issue: Rapid mouse leave from the CursorContainer (especially with multiple CursorContainers on the same page) causes freezing in the container's Cursor. 
Please see issue #1680 for a more detailed breakdown of the problem. 
Attached are gifs from before the change (throttle time at 32ms):
And after the change (throttle time at 16ms):
=> Reduce CursorContainer's onMouseMove throttle

packages/victory-core/src/index.d.ts, packages/victory-tooltip/src/index.d.ts
* Adjusted `labels` prop to accept function that returns array of strings or numbers (which obviously works in JS, but TypeScript complains and `any` assertion is needed)
* Fixed `orientation` prop to accept function that returns `OrientationTypes`, similarly to `pointerOrientation` prop. I removed `VictoryNumberCallback` because I think it doesn't make any sense there, but I'm not 100% sure.
=> Fix MultiLabelableProps and Tooltip orientation TS definitions

packages/victory-histogram/src/helper-methods.js, test/client/spec/victory-histogram/victory-histogram.spec.js
This is to fix #1730 
From the [d3-array docs](https://www.npmjs.com/package/d3-array#bin_thresholds):
Thresholds are defined as an array of values [x0, x1, …]. Any value less than
x0 will be placed in the first bin; any value greater than or equal to x0 but
less than x1 will be placed in the second bin; and so on.
When a `VictoryStack` is used, the `bins` are calculated and passed to `VictoryHistogram` which is why the bug was not present in my repro when I was not using `bins` or `VictoryStack`.
=> Omit first and last bins when specifying d3-array thresholds.

config/webpack/demo/webpack.config.dev-ts.js, config/webpack/demo/webpack.config.dev.js
I was having trouble running up the repository on my machine and after some digging found that it was not recognising the path correctly on my machine. Passing it through `path.normalize()` should make sure that it works fine on either platform.
=> Fix paths in webpack config file for windows machines

config/webpack/demo/webpack.config.dev-ts.js, config/webpack/demo/webpack.config.dev.js, packages/victory-core/src/victory-util/timer.js
I hope I am not stepping on toes with this, but the other [PR](https://github.com/FormidableLabs/victory/pull/1671) tackling this hasn't been updated since August and having the timers run in the background is making it difficult for me to debug something.
This should avoid starting the the timer upon creation and will remove it again when there are no more subscriptions available. I tested this against the animations demo page by clearing the the interval after some time and checking if there was any activity in the background afterwards.
=> Stop timer when there are no subscriptions

config/webpack/demo/webpack.config.dev-ts.js, config/webpack/demo/webpack.config.dev.js, packages/victory-core/src/victory-portal/portal.js, packages/victory-core/src/victory-util/events.js, packages/victory-core/src/victory-util/helpers.js, packages/victory-core/src/victory-util/transitions.js, packages/victory-create-container/src/create-container.js, packages/victory-shared-events/src/victory-shared-events.js
replaces `Object.keys` with lodash `keys` across all packages.
fixes https://github.com/FormidableLabs/victory/issues/1736
=> use lodash keys consistently

packages/victory-core/src/index.d.ts, packages/victory-core/src/victory-container/victory-container.js, test/client/spec/victory-core/victory-container/victory-container.spec.js
This PR adds a `role` prop for `VictoryContainer` (and all the evented containers that extend from it), with a default value of "img". 
Closes https://github.com/FormidableLabs/victory/issues/1741
=> allow user provided roles for VictoryContainer

docs/src/content/guides/events.md
This updates the victory events guide to add some guidance for bypassing the victory events system in favor of native React events, which is mostly what we did on IF/Gates.
=> Add guide for events on custom SVG components

docs/src/content/guides/custom-components.md, docs/src/partials/markdown/index.js
This might be fairly obvious, but it was easy enough to add styled components to the playground and provide an example that uses it to style custom SVG data components.
Let me know if you think this is helpful!
=> Add styled components example to custom components guide

docs/src/content/docs/victory-tooltip.md
Reworded the paragraph to make actual behaviour more explicit.
https://formidable.com/open-source/victory/docs/victory-tooltip#renderinportal
=> Made VictoryTooltip/renderInPortal docs clearer

packages/victory-histogram/src/victory-histogram.js
This PR updates the `bins` prop of `VictoryHistogram` to allow negative numbers as well. For example, `bins={[-20, 0, 20]}` should be allowed.
=> Allow bin prop to be an array of negative numbers as well

packages/victory-core/src/index.d.ts, packages/victory-core/src/victory-primitives/background.js
This PR adds passing along `rx` and `ry` to the `rect` the `Background` primitive renders.
=> Pass rx and ry to Background if provided

docs/src/content/docs/victory-brush-container.md
Add accidentally omitted `handleWidth` prop.
=> fix omission of handleWidth prop for victoryBrushContainer

packages/victory-core/src/index.d.ts
We should change types in getPath. SVG path has string type. In this case it's very important to avoid type errors, when you use library with Typescript.
=> Fix getPath types

docs/src/html.js
Currently the docs on the website show the editable code snippets with double sidebars.
Updating the CodeMirror version seems to fix this.
=> Update CodeMirror version - Fix double scrollbars on the code snippets on the docs

packages/victory-core/src/index.d.ts, test/client/spec/victory-bar/victory-bar.spec.js
The `EventPropTypeInterface` is missing additional parameters that are very useful, e.g., extracting the associated data when an item (bar) is clicked.
Since this is my first PR to this repo (and I reread the contributing guide), I am happy to improving tests and typings. The original expectation in the bar tests seem to not complain about the additional argument, but I added an explicit test just in case.
=> Update EventPropTypeInterface to include prop arg

packages/victory-core/src/index.d.ts
As per https://github.com/FormidableLabs/victory/pull/1575 and https://github.com/FormidableLabs/victory-docs/pull/678, `VictoryLabel` can receive an`id` prop.
=> Add id attribute to VictoryLabelProps interface

demo/js/components/victory-brush-container-demo.js, demo/ts/components/victory-brush-container-demo.tsx, packages/victory-brush-container/src/index.d.ts
This PR adds the `handleWidth` property to the typescript interface. The handleWidth is documented here https://formidable.com/open-source/victory/docs/victory-brush-container#handlewidth but could not be used in typescript.
=> add handleWidth to VictoryBrushContainer interface

.travis.yml, packages/victory-tooltip/src/index.d.ts
fixes https://github.com/FormidableLabs/victory/issues/1810
=> allow setting only x or only y values for VictoryTooltip center prop

packages/victory-brush-container/src/brush-helpers.js
Fixes https://github.com/FormidableLabs/victory/issues/1813
This PR fixes a bug that was causing VictoryBrushContainer to behave incorrectly to clicks outside of the bush area when `allowResize` was set to false. It also makes the fallback `defaultBrushArea` behavior "move" when `allowResize` is false.
=> Fix allowResize false behavior and set defaultBrushArea appropriately

packages/victory-bar/src/helper-methods.js, packages/victory-box-plot/src/helper-methods.js, packages/victory-candlestick/src/helper-methods.js, packages/victory-core/src/victory-animation/victory-animation.js, packages/victory-core/src/victory-util/data.js, packages/victory-errorbar/src/helper-methods.js, packages/victory-histogram/src/helper-methods.js, packages/victory-scatter/src/helper-methods.js, packages/victory-stack/src/helper-methods.js, packages/victory-voronoi/src/helper-methods.js, stories/victory-bar.stories.js, stories/victory-box-plot.stories.js, stories/victory-candlestick.stories.js, stories/victory-errorbar.stories.js, stories/victory-histogram.stories.js, stories/victory-scatter.stories.js
Adds a format data function in global data util to keep data points from reaching out of their supplied domains and to remove points that are entirely outside of the domain.
=> Format Data from Domain

packages/victory-stack/src/helper-methods.js, stories/data.js, stories/victory-area.stories.js, stories/victory-bar.stories.js
Adds support for supplying custom baselines (y0) to the first child in a set of VictoryStack wrapped components, so that they stack correctly based on that first dataset.
Example:
```
<VictoryChart>
<VictoryStack>
<VictoryArea
style={{ data: { fill: "red" } }}
data={[
{ x: 1, y: 2, y0: 1 },
{ x: 2, y: 1, y0: -2 },
{ x: 3, y: 4, y0: 1 },
{ x: 4, y: 2, y0: -3 }
]}
/>
<VictoryArea
data={[
{ x: 1, y: 2 },
{ x: 2, y: 1 },
{ x: 3, y: 4 },
{ x: 4, y: 2 }
]}
/>
<VictoryArea
data={[
{ x: 1, y: 2 },
{ x: 2, y: 1 },
{ x: 3, y: 4 },
{ x: 4, y: 2 }
]}
/>
<VictoryArea
data={[
{ x: 1, y: 1 },
{ x: 2, y: 4 },
{ x: 3, y: 3 },
{ x: 4, y: 8 }
]}
/>
</VictoryStack>
</VictoryChart>
```
Previous:
After:
=> VictoryStack Custom Baseline Support

packages/victory-core/src/index.d.ts
Add missing scale prop type for containers.
fixes https://github.com/FormidableLabs/victory/issues/1831
=> add missing scale for container prop types

packages/victory-box-plot/src/helper-methods.js, packages/victory-candlestick/src/helper-methods.js, packages/victory-core/src/victory-util/data.js, packages/victory-errorbar/src/helper-methods.js, stories/victory-axis.stories.js
Fix for editing data points based on domain when VictoryAxis invertAxis prop is used.
=> Fix - Edit Domain Inverted Axis

packages/victory-core/src/index.d.ts
Hello! First time contributing so please let me know if I need to change anything. This PR fixes:
- added option style prop to group chart definition in `VictoryThemeDefinition`
Thanks!
=> adding the style type to the group chart in main theme definition

packages/victory-core/src/index.d.ts
Fixes the problem raised in issue https://github.com/FormidableLabs/victory/issues/1851.
=> Fixed bug in type definition for EventPropTypeInterface where event handler could not be a void function

docs/src/data/basketball-data.js, packages/victory-core/src/victory-util/domain.js, packages/victory-core/src/victory-util/wrapper.js, stories/victory-bar.stories.js
This PR:
- updates how `domainPadding` is applied to charts when 1) the additional padding _would not_ result new quadradants being added, or 2) the user has set `singleQuadrantDomainPadding={false}`. In these cases, `domainPadding` is applied by calculating a new, smaller range that takes the desired, pixel-based padding into account, and then adding domain padding such that the previous domain fits entirely within the new, smaller range. In most cases, this change will make it much easier to do things like create bar charts where the first bar starts cleanly at the edge of the chart, by setting `domainPadding={{ x: myBarWidth / 2 }}`
**This may cause visual changes for charts that use very large values for `domainPadding`. The `domainPadding` prop may need to be adjusted**
- calculates …
=> experimental domainPadding change

packages/victory-core/src/victory-util/data.js
Fixes a regression in stacked bar charts that have `minDomain` values set. With this change, the `minDomain` is compared against the stacked `_y1` value for each bar rather than the original (unstacked) `_y` value.
=> use y1 for min domain check if it exists

packages/victory-area/src/index.d.ts
This PR fixes https://github.com/FormidableLabs/victory/issues/1864 issue. The function interpolation indeed already works, only type needed updating. 
Let me know if PR needs some updating.
=> added function to the victory area interpolation prop type

.github/workflows/chromatic.yml, packages/victory-axis/src/helper-methods.js
fixes https://github.com/FormidableLabs/victory/issues/1861
This PR corrects an regression introduced in https://github.com/FormidableLabs/victory/pull/1835. Rather than being relative to the origin position, the `offsetX` and `offsetY` props should be relative to the edge of the chart svg.
=> correct axis offsets for multi-quadrant charts

packages/victory-brush-container/src/index.d.ts
VictoryBrushComponentProps.allowDraw? missing from types.
Documented [here](https://formidable.com/open-source/victory/docs/victory-brush-container/#allowdraw) and [in props](https://github.com/FormidableLabs/victory/blob/753f0df6266dbc305cec443c7746298e93f4a207/packages/victory-brush-container/src/victory-brush-container.js#L14)
=> add missing allowDraw property

packages/victory-histogram/package.json, yarn.lock
Downgrades `d3-array` to the version prior to the offending `cumsum` function was introduced.
This is a temporary solution until the problem is solved upstream
fixes https://github.com/FormidableLabs/victory/issues/1877
fixes https://github.com/FormidableLabs/victory-native/issues/653
=> downgrade d3-array

docs/package.json, docs/src/content/common-props/common-props.md, docs/src/content/gallery/discontinuous-scale.md, docs/src/pages/gallery.js, docs/src/partials/markdown/index.js, docs/yarn.lock
This adds some documentation around the existing custom scale prop that can be used to create a discontinuous scale. I included this example as both an example of `scale` on the custom props page, and a gallery example. 
Resolves #1879
=> Custom scale documentation

packages/victory-tooltip/src/victory-tooltip.js
This is a small update that will improve the performance of any component using `VictoryTooltip` without changing the API. 
Currently, every tooltip is getting re-rendered on every interaction, and the `getEvaluatedProps` function gets called on each render. By moving the `active` check to earlier in the render cycle, we can bypass the `getEvaluatedProps` function if the tooltip is not active, reducing scripting time for inactive tooltips. 
For a `VictoryScatter` chart with 2000 data points and tooltips running in production:
|          | scripting time | rendering time | lighthouse performance score |
|------|---------|-----------|-------------------------------|
|before|892ms|16ms|80|
|after|660ms|19ms|88|
Related issues: #1669, #1621, #1614
=> Improve VictoryTooltip rendering performance

packages/victory-core/src/victory-util/wrapper.js
encountered a minor error related to recent changes in automatic `barWidth` calculation for grouped bars. This PR adds a quick check for the existence of children
=> add a check for children before attempting barWidth calculation

packages/victory-area/package.json, packages/victory-axis/package.json, packages/victory-bar/package.json, packages/victory-box-plot/package.json, packages/victory-brush-container/package.json, packages/victory-brush-line/package.json, packages/victory-candlestick/package.json, packages/victory-chart/package.json, packages/victory-core/package.json, packages/victory-create-container/package.json, packages/victory-cursor-container/package.json, packages/victory-errorbar/package.json, packages/victory-group/package.json, packages/victory-histogram/package.json, packages/victory-legend/package.json, packages/victory-line/package.json, packages/victory-pie/package.json, packages/victory-polar-axis/package.json, packages/victory-scatter/package.json, packages/victory-selection-container/package.json, packages/victory-shared-events/package.json, packages/victory-stack/package.json, packages/victory-tooltip/package.json, packages/victory-voronoi-container/package.json, packages/victory-voronoi/package.json, packages/victory-zoom-container/package.json, packages/victory/package.json, yarn.lock
This PR adds `react` as a peerDependency to all victory packages. 
Closes https://github.com/FormidableLabs/victory/issues/1914
=> add react as a peerDependnecy to all victory packages

packages/victory-core/src/index.d.ts
Added an optional rx and ry prop to `VictoryPrimitiveShapeProps` as mentioned on https://github.com/FormidableLabs/victory/issues/1893.
=> Update interface with optional rx ry

README.md, docs/src/content/faq/faq.md, docs/src/partials/home/_content.js, docs/src/partials/sidebar/components/introduction.js, docs/static-config-helpers/site-data.js
Since spectrum is becoming read only, we should remove references to spectrum from Victory's docs site
=> remove spectrum links and references

package-scripts.js
- Remove `--colors` flag from webpack CLI invocations
- Add `check.ci` step to build webpack dev + prod builds
Fixes #1919
=> FIX: Fix webpack5 cli build and add dists creation to CI.

packages/victory/src/index.js
I noticed that we also have a large default export in `victory/index`. Updating this to the ESM export syntax shouldn't change the imports.
=> Update export syntax in victory index

packages/victory-core/src/victory-util/events.js
- Remove invalid `this.` references to exported components from after our refactor away from default exports. Fixes #1930 
@dev-yakuza I tried this out in your repo (after doing a build in this branch `victory` repo and copying over `victory/package/victory-core` to replace `node_modules/victory-core`) and I no longer get your production error. Would love to hear if you could confirm on your end?
=> Bugfix: Remove invalid this references

packages/victory-group/src/victory-group.js, packages/victory-stack/src/victory-stack.js
This applies the same refactor from VictoryGroup in #1931 to VictoryStack. This one has about the same before and after performance, because we weren't seeing as much re-rendering with VictoryStack originally.
Before: 
After:
=> Refactor VictoryStack

packages/victory-core/src/index.js, packages/victory-core/src/victory-util/wrapper.js, test/client/spec/victory-core/victory-util/wrapper.spec.js
Removes default export in wrapper.js and removes unused functions (that have been moved to hooks.js). It's a bit hard to read the diff, but the functions have just been re-ordered in order to prevent calling the function before declaring it.
This also removes the unused sinon spy that was causing an error (there were no assertions on the sandbox).
=> Update wrapper export syntax

packages/victory-core/src/index.d.ts
My TSLint is currently throwing an error when trying to implement a custom theme function that returns a `VictoryThemeDefinition`
```
Object literal may only specify known properties, and 'histogram' does not exist in type 'VictoryThemeDefinition'.ts
```
This assumes that the histogram styles are fundamentally the same as the `VictoryBar` component
=> Add histogram to VictoryThemeDefinition interface

packages/victory-core/package.json, yarn.lock
Originally I had intended to upgrade other d3 packages as well to avoid similar issues in the future, but I ran into [this issue](https://github.com/d3/d3-voronoi/issues/16) in `victory-voronoi.spec.js` after upgrading other d3 packages.  
Fixes #1945
=> Upgrade d3 interpolate

packages/victory-area/package.json, packages/victory-axis/package.json, packages/victory-bar/package.json, packages/victory-box-plot/package.json, packages/victory-brush-container/package.json, packages/victory-brush-line/package.json, packages/victory-candlestick/package.json, packages/victory-chart/package.json, packages/victory-core/package.json, packages/victory-create-container/package.json, packages/victory-cursor-container/package.json, packages/victory-errorbar/package.json, packages/victory-group/package.json, packages/victory-histogram/package.json, packages/victory-legend/package.json, packages/victory-line/package.json, packages/victory-pie/package.json, packages/victory-polar-axis/package.json, packages/victory-scatter/package.json, packages/victory-selection-container/package.json, packages/victory-shared-events/package.json, packages/victory-stack/package.json, packages/victory-tooltip/package.json, packages/victory-voronoi-container/package.json, packages/victory-voronoi/package.json, packages/victory-zoom-container/package.json, packages/victory/package.json
`nps` devDependency was not being prodived in the same way with lerna update, so this alters the version script that runs on publish. Oddly, this was not caught with the version dry run, which is using `lerna version` rather than `lerna publish` .
=> modify version scripts in individual packages

packages/victory-core/package.json, yarn.lock
Here's a bandaid for the CJS / ESM issue introduced with the recent update to `d3-interpolate`. That update was motivated by a security issue in the `d3-color` dependency. This PR reverts the `d3-interpolate` update, but adds a resolution for `d3-color` to address the security issue. This should get around the ESM issue we were seeing with `d3-interpolate`, because Victory does not directly import `d3-color`. Phew!
=> revert d3-interpolate while updating only d3-color

docs/src/pages/gallery.js
Right now, on the gallery page of the docs, each gallery item is wrapped in a `Link`, so that the interactive chart is wrapped by the `Link`. This entails that when you interact with one of the gallery items, and `mouseup`, the `Link` is activated. This is shown here:
https://user-images.githubusercontent.com/12721310/135670103-9d7e5966-d194-4d81-ae2e-0c69c2ea49f2.mp4
This PR proposes moving the chart preview _outside_ of the `Link`, and only have the title contained by the `Link` -- which is probably a more semantic usage of `Link`, and avoids this behavior. This updated behavior is shown here:
https://user-images.githubusercontent.com/12721310/135670193-a4eea1b3-5e6e-46eb-957f-42244cea1684.mp4
=> Gallery Page: small tweaks to `Link` placement

packages/victory-group/src/index.d.ts
We plan to remove implicit types for `children` in `@types/react@18.x`. 
I ran `yarn nps compile-ts` and only `VictoryGroup` was reporting failures when `children` weren't added by `@types/react`.
=> Add explicit types for VictoryGroup#children

.eslintignore, .eslintrc.js, .github/workflows/ci.yml, babel-native-config.js, jest-native-config.js, jest-native-setup.js, package-scripts.js, package.json, packages/victory-native/src/index.d.ts, test/client/main.js, test/jest/components.test.js, test/jest/native-helpers.test.js, tsconfig.json, yarn.lock
This PR ports over the test from the `victory-native` repo into this one! A couple things to note:
- I decided to go with Jest as the test runner here, as I expect a potential migration from mocha/chai over to Jest.
- I added a `jest` script to the `package-scripts`, but they're tailored to the native tests. Eventually there might be more scripts pertain to the core libraries.
- There is jest/babel setup specifically for the native tests, since testing RN libraries is... hard... and requires additional setup.
=> Native tests!

packages/victory-chart/src/victory-chart.js, packages/victory-core/src/index.js, packages/victory-core/src/victory-util/hooks/index.js, packages/victory-core/src/victory-util/hooks/use-animation-state.js, packages/victory-core/src/victory-util/hooks/use-previous-props.js, packages/victory-group/src/victory-group.js, packages/victory-stack/src/victory-stack.js
This moves some files around and adds a Hooks namespace to make it easier to add to the Victory custom hooks without adding more lines of code to `hooks.js`.
=> Add Hooks namespace to maintain consistency with helpers

README.md, packages/victory-native/README.md
This PR moves the Victory Native README into the `packages/victory-native` package here, and updates some of the demo instructions accordingly.
=> Absorb victory-native README/docs

packages/victory-native/src/components/victory-brush-container.js
Fixed bug on react native for touch events for VictoryBrushContainer.
It's related to issue: https://github.com/FormidableLabs/victory/issues/2021
=> Fix for victory-native touch events in VictoryBrushContainer

packages/victory/src/index.d.ts
Reverts FormidableLabs/victory#2058
Well, apparently this broke the typescript build for TS projects importing Victory. Let's revert this fix for now, and include these types in #2059. I will also add a ticket to make sure the `nps build-ts` command is actually catching these sorts of build failures, because we should try to catch this in CI.
=> Revert "Uncomment type definitions for VictorySelectionContainer"

docs/src/partials/home/features.js, docs/src/partials/home/more-oss.js
Fixes up the font stack that appears on the docs page and matches the margins with Renature:
Proposed: 
Current:
=> Fix font stack and correct margins in docs

CHANGELOG.md, docs/src/content/docs/victory-label.md
Hello!
I noticed the docs and typescript were missing the `textComponent` prop on `VictoryLabel` which I needed to overwrite.
Here is PR fixing that.
=> Patch missing text component type

packages/victory-native/src/components/victory-container.js
This adjusts the markup of the native `VictoryContainer` so that it's always rendering its children within an `Svg` element. My hunch is that this seems to fix touch issues on Android because `react-native-svg`'s `Svg` is central to its own implementation of touch events. See [here](https://github.com/react-native-svg/react-native-svg/blob/develop/android/src/main/java/com/horcrux/svg/SvgView.java) to see methods like `hitTest` and `interceptsTouchEvent`. This is why previously proposed solutions like [this](https://github.com/FormidableLabs/victory/issues/2031#issuecomment-1011077399) and [this](https://github.com/FormidableLabs/victory/issues/2031#issuecomment-1020921557) seem to fix the issue.
Currently, the `View` below the main `Svg` is positioned absolutely on top of it, and then …
=> fix: android touch events

packages/victory-voronoi-container/src/index.d.ts
typings for ```voronoiBlacklist``` do not currently include regular expressions, which are supported as of [this](https://github.com/FormidableLabs/victory/pull/1278) PR. This changes the type so ```voronoiBlacklist``` correctly allows both strings and regular expressions.
=> Add RegExp array to voronoiBlacklist type

tsconfig.json
In the main code of the project, all packages have `index.d.ts` files. `skipLibCheck` is set to `true` in the project `tsconfig.json`, which means that unimplemented types can slip through these files without causing a compile error. These errors can then show up after a build release, when users install Victory into their TypeScript projects and set `skipLibCheck` to `true`.
- In `tsconfig.json`
```diff
{
"compilerOptions": {
"baseUrl": ".",
"outDir": "demo/dist",
"rootDir": ".",
"module": "es6",
"target": "es5",
"jsx": "react",
"sourceMap": true,
"moduleResolution": "node",
+   "typeRoots": [
+     "./node_modules/@types"
+   ],
+   "types": ["react", "lodash"],
"allowSyntheticDefaultImports": true,
"forceConsistentCasingInFileNames": true,
"noImplicitReturns": true,
"noImplicitThis": …
```
=> Fix TS build 2094

packages/victory-zoom-container/src/zoom-helpers.js
This is in regards to this bug reported for horizontal graphs: https://github.com/FormidableLabs/victory/issues/2083
When a chart is set to horizontal mode and is zoomed and panned, the panning rate is not 1:1 with mouse movement.
It looks like getDomainScale is setting the range incorrectly.
```
getDomainScale(domain, scale, axis, horizontal) {
const axisDomain = Array.isArray(domain) ? domain : domain[axis];
const [from, to] = axisDomain;
const otherAxis = axis === "x" ? "y" : "x";
const range = horizontal ? scale[otherAxis].range() : scale[axis].range();
const plottableWidth = Math.abs(range[0] - range[1]);
return plottableWidth / (to - from);
},
```
const range does not need to switch the axis - scale already handles that:
```
const scale = {
x: Scale.getBaseScale(props, "x") …
```
=> Fix Horizontal charts panning at the incorrect rate

demo/js/components/victory-chart-demo.js, packages/victory-chart/src/victory-chart.js
- When running the Chrome/Edge Accessibility Insights tool, the `VictoryCharts` component throws the error below due to missing alternate text:
- Added the ability to add a title and description to the `VictoryChart` svg component: 
- Tested manually by adding the new title and description props to some of the `VictoryCharts` components within the `victory-chart-demo.js` file and running the accessibility tool:
All `VictoryChart` components with the new title and desc props present pass with no errors, while the rest still fail.
This PR is created to resolve this issue: https://github.com/FormidableLabs/victory/issues/2078 
Accessibility tool: https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni?msclkid=e63b5c6bc02e11ec9e1dd5de91f4d99d
=> Added the ability to add victory charts title and desc props for better accessibility

packages/victory-pie/src/index.d.ts
This PR address #2090 and adds `VictoryStyleInterface` as an optional `style` value to the `SliceProps` type declaration. This matches behavior and [the documentation](https://formidable.com/open-source/victory/docs/victory-primitives/#slice) for this component.
=> add style interface to SliceProps type

docs/src/content/common-props/common-props.md
After brushing up a little more on how the `scale` prop works, I noticed a few tiny grammatical issues in the [scale prop documentation](https://formidable.com/open-source/victory/docs/common-props/#scale).
=> fix typos in scale prop documentation

test/jest/victory-box-plot/victory-box.plot.test.js
Part of effort #2195, updating box-plot unit tests to use Jest and React Test Library. 
These tests can be run with the command
```
yarn nps jest
```
=> add box plot jest/rtl tests

test/jest/victory-brush-container/brush-helpers.test.js
Part of #2195, this migrates the existing `brush-helpers` tests to Jest. This covers the existing unit tests for `victory-brush-container`.
=> brush container helper jest tests

packages/victory-core/src/victory-label/victory-label.js, test/jest/rendering-utils.js, test/jest/victory-core/victory-accessible-group/victory-accessible-group.test.js, test/jest/victory-core/victory-animation/util.test.js, test/jest/victory-core/victory-container/victory-container.test.js, test/jest/victory-core/victory-label/victory-label.test.js, test/jest/victory-core/victory-primitives/clip-path.test.js, test/jest/victory-core/victory-primitives/curve.test.js, test/jest/victory-core/victory-primitives/line.test.js, test/jest/victory-core/victory-primitives/point.test.js, test/jest/victory-core/victory-primitives/slice.test.js, test/jest/victory-core/victory-util/axis.test.js, test/jest/victory-core/victory-util/collection.test.js, test/jest/victory-core/victory-util/data.test.js, test/jest/victory-core/victory-util/domain.test.js, test/jest/victory-core/victory-util/events.test.js, test/jest/victory-core/victory-util/helpers.test.js, test/jest/victory-core/victory-util/label-helpers.test.js, test/jest/victory-core/victory-util/point-path-helpers.test.js, test/jest/victory-core/victory-util/prop-types.test.js, test/jest/victory-core/victory-util/scale.test.js, test/jest/victory-core/victory-util/selection.test.js, test/jest/victory-core/victory-util/style.test.js, test/jest/victory-core/victory-util/textsize.test.js, test/jest/victory-core/victory-util/transitions.test.js, test/jest/victory-core/victory-util/wrapper.test.js
This is part of the work for #2195.
* Copies existing spec files, runs codemod to change expectations
* Replaces enzyme with RTL
Note: This does not include the tests for `add-events`. These tests were the most complex to convert (there is a lot of mocking going on in the current test implementation), and this `addEvents` HOC is also one of my top priorities for refactoring out of the codebase. I personally am okay with letting these tests go for now, and then adding additional test coverage once we have a better solution for all this shared logic.
=> Add victory core tests

CHANGELOG.md, docs/src/content/common-props/common-props.md, docs/src/content/docs/victory-shared-events.md, docs/src/content/guides/events.md, packages/victory-core/src/victory-util/common-props.js, packages/victory-legend/src/victory-legend.js, packages/victory-pie/src/victory-pie.js, packages/victory-shared-events/src/victory-shared-events.js
Fixes https://github.com/FormidableLabs/victory/issues/2063
Several places in Victory reference non-existent `PropTypes.function` validator. This seem to be a common error, as exactly the same case is pointed out in `prop-types` codebase:
https://github.com/facebook/prop-types/blob/4de0644a10a554d0a556daa39f029369bc007ea5/checkPropTypes.js#L55-L57
This causes warning in console:
```
'Warning: Failed prop type: VictoryScatter: prop type externalEventMutations[0].callback is invalid; it must be a function, usually from the prop-types package, but received undefined.'
```
This PR replaces validators with `PropTypes.func` (https://github.com/facebook/prop-types#usage)
=> [FIX] Replace references to non-existent PropTypes.function with PropTypes.func

packages/victory-area/src/victory-area.js, packages/victory-bar/src/victory-bar.js, packages/victory-box-plot/src/victory-box-plot.js, packages/victory-candlestick/src/victory-candlestick.js, packages/victory-core/src/victory-clip-container/victory-clip-container.js, packages/victory-core/src/victory-util/add-events.js, packages/victory-core/src/victory-util/user-props.js, packages/victory-errorbar/src/victory-errorbar.js, packages/victory-histogram/src/victory-histogram.js, packages/victory-line/src/victory-line.js, packages/victory-pie/src/victory-pie.js, packages/victory-scatter/src/victory-scatter.js, packages/victory-voronoi/src/victory-voronoi.js, test/jest/rendering-utils.js, test/jest/victory-area/victory-area.test.js, test/jest/victory-bar/victory-bar.test.js, test/jest/victory-box-plot/victory-box-plot.test.js, test/jest/victory-candlestick/victory-candlestick.test.js, test/jest/victory-line/victory-line.test.js
This fixes a bug that Paul and I were running into where the user props like `data-testid` and `aria-label` were being passed in to both the container and the group component, so even when we were rendering a victory data component as a standalone component (without a container or VictoryChart wrapper), `screen.getByTestId` was returning multiple nodes in the tests rather than the parent wrapper component.
In order to fix this, I removed the user props logic from the `renderData` function in `add-events`, and passed the user props into the root component that was returned from a Victory component rather than the container. This ensures that the props will be passed into either the `svg` or the `g` component, depending on whether there is another container present. I also added some …
=> Fix duplicate user props

test/jest/victory-legend/victory-legend.test.js, test/svg-test-helper.js
Part of #2195 to update tests, this PR adds the existing `victory-legends` tests to the Jest/RTL test suite.
=> migrate existing legend tests to jest

packages/victory-errorbar/src/error-bar.js, test/jest/rendering-utils.js, test/jest/victory-core/victory-accessible-group/victory-accessible-group.test.js, test/jest/victory-core/victory-label/victory-label.test.js, test/jest/victory-core/victory-primitives/clip-path.test.js, test/jest/victory-core/victory-primitives/curve.test.js, test/jest/victory-core/victory-primitives/line.test.js, test/jest/victory-core/victory-primitives/point.test.js, test/jest/victory-core/victory-primitives/slice.test.js, test/jest/victory-errorbars/error-bar.test.js, test/jest/victory-errorbars/victory-errorbars.test.js, test/jest/victory-tooltip/flyout.test.js
This is part of #2195 
This also includes removing the `renderInSvg` function and using `{ wrapper: 'svg' }` instead. I meant to push up this change as a separate PR, but it ended up here instead.
=> Convert tests for victory error bar

package-scripts.js, packages/victory-vendor/package.json, packages/victory-vendor/scripts/build.js
Adds the following to our `package.json:exports` for more flexible consumption:
- Add `package.json:exports` for `package.json`. This is generally useful to have for npm packages using exports to introspect the project itself.
- Add `package.json:exports` for `lib/*` consumers can point to CommonJS directly.
- Add `package.json:exports` for `es/*` consumers can point to ESM directly.
Additional things:
- Fix our `build.js` script to not errantly output an empty `victory-vendor/d3-*` directory.
Fixes #2250
=> victory-vendor: script cleanup and exports enhancements

test/jest/victory-pie/victory-pie.test.js, test/svg-test-helper.js
Part of #2195 - this PR migrates the existing `victory-pie` unit tests to Jest and RTL.
=> victory-pie jest/rtl tests

.eslintrc.js, docs/src/partials/markdown/index.js, docs/static-config-helpers/get-md-files.js, docs/static-config-helpers/md-data-transforms.js, packages/victory-chart/src/helper-methods.js, packages/victory-core/src/victory-util/axis.js, packages/victory-core/src/victory-util/collection.js, packages/victory-core/src/victory-util/data.js, packages/victory-core/src/victory-util/default-transitions.js, packages/victory-core/src/victory-util/domain.js, packages/victory-core/src/victory-util/events.js, packages/victory-core/src/victory-util/helpers.js, packages/victory-core/src/victory-util/immutable.js, packages/victory-core/src/victory-util/label-helpers.js, packages/victory-core/src/victory-util/log.js, packages/victory-core/src/victory-util/prop-types.js, packages/victory-core/src/victory-util/scale.js, packages/victory-core/src/victory-util/selection.js, packages/victory-core/src/victory-util/style.js, packages/victory-core/src/victory-util/transitions.js, packages/victory-core/src/victory-util/wrapper.js, packages/victory-group/src/helper-methods.js, packages/victory-stack/src/helper-methods.js
We are disabling this eslint rule in many places, and personally I don't think enforcing `const` over `function` syntax has a lot of value. Any objections to disabling it and moving on with our lives?
=> Disable func-style eslint rule

.eslintrc.js, demo/js/components/victory-label-demo.js, demo/ts/components/victory-label-demo.tsx, package.json, packages/victory-create-container/src/create-container.js, test/client/spec/victory-core/victory-primitives/slice.spec.js, yarn.lock
This plugin enforces some rules for `// eslint-disable` style comments.  
Mainly, this requires us to clean-up any comments that are no longer necessary!
=> Enable `eslint-comments`

.babelrc.js, package.json, packages/victory-core/src/victory-animation/victory-animation.tsx, packages/victory-core/src/victory-portal/victory-portal.tsx, packages/victory-core/src/victory-transition/victory-transition.tsx, packages/victory-core/src/victory-util/add-events.js
- Use named import for `addEvents > Transition` dependency
- Properly type the `context` property for class components, so that it doesn't get initialized
- Adds "optional chaining" transpilation to Babel
These issues were all found in React Native, although it's not specific to that.
To test:
```
cd demo/rn
yarn start
```
Open in iOS simulator, and verify that all demos are working as expected.
=> TypeScript: fix a few build issues

packages/victory-core/src/victory-util/common-props.tsx
Marks `data` as `readonly`.
We don't mutate the data, so this doesn't break anything, and doesn't require any other changes.
Fixes #2309
=> TypeScript: Mark `data` as `readonly`

package.json, packages/victory-core/src/victory-state/victory-provider.tsx, yarn.lock
This removes our dependency on use-context-selector in favor of vanilla context. Once we have a more fully-featured re-write, we can do some performance comparisons and measure whether something like `use-context-selector` provides noticeable performance gains, and reconsider introducing something similar. 
Fixes #2322
=> Remove dependency on use-context-selector

.vscode/settings.json
`.vscode` is git-ignored, and I'm generally a fan of keeping IDE settings out of repos. However, I'm proposing we add a small amount of workspace/local settings to make search more useful. With the es/cjs build folders, searching for a file ends up showing triple the results. This PR excludes the es/lib results from that search.
=> Local VSC settings to ignore built files in search

packages/victory-chart/src/victory-chart.test.js, packages/victory-core/src/victory-util/hooks/use-animation-state.js
I'm not exactly sure why this is _just now_ becoming an issue, but somehow a `props` value is `undefined` (I think on just first render) and it was throwing because of a property-lookup on `undefined`. Seems like _maybe_ because `usePreviousProps` is always going to return `undefined` on first render until the `useEffect` therein kicks in.
Nevertheless, this fix seems to resolve the issue reported in #2329.
=> Fix for #2329 (use-animation-state crashing charts)

package.json, packages/victory-area/package.json, packages/victory-axis/package.json, packages/victory-bar/package.json, packages/victory-box-plot/package.json, packages/victory-brush-container/package.json, packages/victory-brush-line/package.json, packages/victory-candlestick/package.json, packages/victory-canvas/package.json, packages/victory-chart/package.json, packages/victory-core/package.json, packages/victory-create-container/package.json, packages/victory-cursor-container/package.json, packages/victory-errorbar/package.json, packages/victory-group/package.json, packages/victory-histogram/package.json, packages/victory-legend/package.json, packages/victory-line/package.json, packages/victory-pie/package.json, packages/victory-polar-axis/package.json, packages/victory-scatter/package.json, packages/victory-selection-container/package.json, packages/victory-shared-events/package.json, packages/victory-stack/package.json, packages/victory-tooltip/package.json, packages/victory-voronoi-container/package.json, packages/victory-voronoi/package.json, packages/victory-zoom-container/package.json, packages/victory/package.json, scripts/sync-pkgs-wireit-helpers.js
This is the cause of the CI failures in https://github.com/FormidableLabs/victory/pull/2379
- Pkg format incorrectly checked if _lint_ succeeded first.
- Root pkg fix needed conditional check.
=> Infra/Bug: Fix format tasks

packages/victory-bar/package.json, packages/victory-line/package.json, pnpm-lock.yaml
Changesets can't handle references like:
```js
"devDependencies": {
"victory-line": "."
}
```
so we're switching to:
```js
"devDependencies": {
"victory-line": "*"
}
```
See, e.g. https://github.com/FormidableLabs/victory/runs/7617438496?check_suite_focus=true
```
> pnpm changeset version && pnpm install
🦋  error TypeError: Invalid comparator: .
🦋  error     at Comparator.parse (/home/runner/work/victory/victory/node_modules/.pnpm/semver@5.7.1/node_modules/semver/semver.js:754:11)
🦋  error     at new Comparator (/home/runner/work/victory/victory/node_modules/.pnpm/semver@5.7.1/node_modules/semver/semver.js:737:8)
🦋  error     at Range.<anonymous> (/home/runner/work/victory/victory/node_modules/.pnpm/semver@5.7.1/node_modules/semver/semver.js:925:12)
🦋  error     at Array.map (<anonymous>) …
```
=> Bug: Fix victory devDeps references.

package.json
In CI, `pnpm install` checks against lockfile for changes and fails. We _want_ lockfile changes in our version script, so explicitly allow.
See, e.g.: https://github.com/FormidableLabs/victory/runs/7618211238?check_suite_focus=true
=> Bug: Add pnpm install --no-frozen-lockfile to version script

.github/workflows/ci.yml
Currently we skip CI checks for doc-only changes.
However, since these checks are "Required", it blocks doc-only PRs from merging.
This PR will run CI checks for any changes, even if doc-only.
=> chore(build): Run checks even for doc-only changes

packages/victory-axis/src/victory-axis.tsx, packages/victory-box-plot/src/victory-box-plot.tsx, packages/victory-chart/src/helper-methods.test.tsx, packages/victory-core/src/victory-util/add-events.tsx, packages/victory-core/src/victory-util/axis.test.tsx, packages/victory-core/src/victory-util/wrapper.test.tsx, packages/victory-errorbar/src/victory-errorbar.tsx, packages/victory-scatter/src/victory-scatter.test.tsx, packages/victory-scatter/src/victory-scatter.tsx, packages/victory/src/victory.test.ts
4 of our packages were being exported as `any`, like `export declare const VictoryAxis: any;`
This was due to excessively complex issues with the `addEvents` mixin.
This PR fixes that, adds unit tests for all components, and improves various types to work with the fixed type.
Fixes #2411
=> TS Migrate: fixed type issues

packages/victory-core/src/types/callbacks.ts, packages/victory-core/src/victory-label/victory-label.tsx
This improves the callback signature for the `textAnchor` prop.
Fixes #2361
=> chore(typescript): improved `textAnchor` props for `victory-label`

packages/victory-core/src/victory-util/events.ts, packages/victory-core/src/victory-util/user-props.ts
Replaced Template Literal Types since they're a newer TS feature (starting in 4.1).
Replaced with simply `string` types.
These types were nice to have, but weren't extremely useful, so we decided to loosen up the types.
Fixes #2409
=> chore: Removed Template Literal Types to increase TS compatibility

.changeset/spicy-books-search.md, .eslintrc.js, packages/victory-cursor-container/src/cursor-helpers.tsx, packages/victory-line/src/v37/victory-line.stories.tsx, stories/victory-tooltip.stories.js
An import statement incorrectly referenced `victory-core/src`, which caused all source code to try to be compiled.
=> TypeScript: fixed broken import

packages/victory-canvas/src/index.d.ts, packages/victory-create-container/src/index.d.ts, packages/victory-selection-container/src/index.d.ts, packages/victory-voronoi-container/src/index.d.ts, packages/victory-zoom-container/src/index.d.ts
In https://github.com/FormidableLabs/victory/commit/5a4fc5be26f3b04e3d335625e72df5482d1150b8 I added several missing types to our `index.d.ts` files.  I added these with implicit `any` parameters.
Since these `.d.ts` files get **copied**, not **compiled**, they don't automatically get explicit `:any` types.
This caused #2358 for consumers who have "no implicit any" configurations.
This PR adds explicit `:any` types to all these parameters.
I considered adding "good" types for these methods. But since all these types will eventually be made obsolete once we convert these packages to TypeScript, it makes more sense to just add `:any` here for now, and allow the TS migration to handle improved types.
=> Chore: added explicit `any` types to exported methods

.changeset/quiet-dogs-serve.md, packages/victory-core/src/types/callbacks.ts, packages/victory-core/src/types/prop-types.ts, packages/victory-core/src/victory-label/victory-label.tsx, packages/victory-core/src/victory-util/helpers.ts, packages/victory-cursor-container/src/victory-cursor-container.tsx
The common props `x`, `y`, `y0`, and `sortKey` allow for "accessor" functions, like:
```
<VictoryLine
data={data}
x = {(datum) => datum.xValue}
y = {(datum) => datum.yValue}
/>
```
Currently, we have the `datum` arg typed as `object`, which doesn't allow for any property access nor strong types (see #2360).
This PR allows for the type to be `any`.  This seems like the best approach, since we currently don't know the shape of Datum, nor do we support generics with any of our components.
This will allow the above code to function properly, as well as support manually-added types (like `(datum: MyData) => datum.xValue`).
=> Fix (TypeScript): give `datum` an `any` type

.changeset/swift-singers-reply.md, packages/victory-brush-container/src/victory-brush-container.tsx, packages/victory-cursor-container/src/victory-cursor-container.tsx, packages/victory-selection-container/src/victory-selection-container.js, packages/victory-voronoi-container/src/victory-voronoi-container.js, packages/victory-zoom-container/src/victory-zoom-container.js
Before TS conversion, we were falsely exporting a `class Victory___Container`, which serves as both a value and a type.
After TS conversion, we are now exporting just a value, `const Victory___Container = mixin(...)`, which no longer serves as a type.
This broke our `victory-native` types, since we were using it as a type.  However, this went unchecked, because we don't type-check our `.d.ts` files.
With this PR, I am now exporting both the value and the type. 
I have also left some comments in some JS files where this problem will occur once converting to TS.
Addresses #2451
=> TS: Fixed the exported types for all containers

packages/victory-line/src/victory-line.tsx
This fixes a TypeScript error where `VictoryLine`'s `animate` type inadvertently overrides `VictoryCommonProps`. According to the  `VictoryLine` docs, the `animate` prop should accept `boolean | AnimatePropTypeInterface`.
Closes: https://github.com/FormidableLabs/victory/issues/2463
=> VictoryLine's animate type overrides VictoryCommonProps

.changeset/breezy-berries-fix.md, .github/workflows/release.yml
To help resolve #2434 - I believe this [thread](https://github.com/changesets/action/issues/187) and [solution](https://github.com/changesets/action/issues/187#issuecomment-1228413850) outline a potential temporary fix.
A token was generated (details to be provided in Slack) and this has been setup in the `release.yml` workflow.
Hopefully this works and correctly runs the workflows as the `victory-ci` user without us needing to close and re-open the PR!
We will need to test this properly after a merge to review if the "Version Packages" PR that is opened runs the CI tests/suite as expected. If it does, we do not need to revert this change. If it does not, then this change has not been worthwhile in fixing this bug
=> use different GitHub token for Version Packages

CONTRIBUTING.md, README.md, docs/src/content/common-props/common-props.md, docs/src/content/docs/victory-area.md, docs/src/content/docs/victory-axis.md, docs/src/content/docs/victory-boxplot.md, docs/src/content/docs/victory-brush-container.md, docs/src/content/docs/victory-brush-line.md, docs/src/content/docs/victory-candlestick.md, docs/src/content/docs/victory-chart.md, docs/src/content/docs/victory-clip-container.md, docs/src/content/docs/victory-errorbar.md, docs/src/content/docs/victory-group.md, docs/src/content/docs/victory-histogram.md, docs/src/content/docs/victory-label.md, docs/src/content/docs/victory-legend.md, docs/src/content/docs/victory-line.md, docs/src/content/docs/victory-polar-axis.md, docs/src/content/docs/victory-primitives.md, docs/src/content/docs/victory-selection-container.md, docs/src/content/docs/victory-tooltip.md, docs/src/content/docs/victory-voronoi-container.md, docs/src/content/docs/victory-zoom-container.md, docs/src/content/faq/faq.md, docs/src/content/guides/events.md, docs/src/content/guides/tooltips.md, docs/src/content/guides/zoom-large-data.md, docs/src/content/introduction/native.md, docs/src/content/introduction/new.md
I used the [Grammarly extension for VS Code](https://marketplace.visualstudio.com/items?itemName=znck.grammarly&ssr=false#overview) to find issues.
=> Docs: fix typos and grammatical errors

.changeset/strange-mangos-leave.md, packages/victory-native/package.json
- Adds `react` as a peerDependency for `react-native`
- Addresses #2478
=> Chore: added `react`  as a peer dependency to `react-native`

.changeset/few-owls-end.md, packages/victory-stack/src/victory-stack.tsx
- Adds strong types to `victory-stack` props
- Addresses #2449
=> Typescript: victory-stack props

config/webpack/demo/webpack.config.dev.js, packages/victory-vendor/.babelrc.js
Some of the tools used in the build process (particularly in the webpack dev server flow) fall apart when using windows-style paths, with backslashes (\\) instead of forward slashes (/).
This PR normalizes paths in the places where it affects the build, allowing `pnpm start` to fully function on windows machines, while not affecting builds on *nix systems.
=> Fix path issues when building on windows os

.changeset/pretty-moles-laugh.md, .storybook/main.js, packages/victory-core/src/victory-util/textsize.test.ts, packages/victory-core/src/victory-util/textsize.ts, packages/victory-vendor/.babelrc.js, stories/victory-label.stories.js
Addresses https://github.com/FormidableLabs/victory/issues/2475
As mentioned in the issue, the tooltip can appear to not have accurate sizing/padding in some cases.
I investigated and found that the tooltip tries to approximate the size that the text content will be, and then uses that to then size the tooltip box around the text. The logic for this size approximation lives [here](https://github.com/FormidableLabs/victory/blob/main/packages/victory-core/src/victory-util/textsize.ts).
The logic for approximating the text size involves reading from a list of hard-coded font metadata, and computing styles and glyph widths to reach a final width and height. (`victory-tooltip` then adds the padding, and uses that for the size of the tooltip).
There's a few issues with this, the primary being …
=> Fix inaccurate text size calculations

.github/workflows/docs.yml, docs/static-config-helpers/constants.js
This PR drops Surge for preview deploys in favor of Vercel, and sets up build config to work for staging previews + "production stitching" into formidable.com. [Example staging preview here](https://victory-pbo02en91-formidable-labs.vercel.app/).
=> Vercel for Staging Previews

.changeset/short-countries-serve.md, packages/victory-core/src/victory-util/textsize.ts, stories/victory-legend.stories.js
fix for https://github.com/FormidableLabs/victory/issues/2613
I made a change a while back to improve the text size calculations, which were inadequate when using certain fonts or character sets, such as arabic or chinese.
It was recently discovered that this change also regressed calculations involving line-height. It turns out, setting line-height on an svg text element does not appear to have any effect. This PR fixes that regression by manually computing line-height per-line using the rendered text height multiplied by the desired line-height.
=> Improve lineheight calc in measureDimensions

.changeset/many-suns-hang.md, packages/victory-core/src/victory-util/textsize.ts
The `testsize` util creates a hidden SVG element, but does not set `aria-hidden` to `true`, which causes accessibility issues. This PR simply adds the attribute.
=> Add aria-hidden flag to svg for textsize util to fix accessibility issue

.changeset/orange-timers-run.md, packages/victory-bar/src/bar.js, packages/victory-core/src/victory-primitives/path.tsx, stories/victory-bar.stories.js
This will allow the user to pass in a `ref` to the `<Bar />` component when using the custom `dataComponent` prop for `<VictoryBar />`. This will allow users to set individual refs for each bar in their data set as well if they use a ref map and ref callback, allowing for better accessibility options.
See "Focus With Refs" story under VictoryBar stories when running Storybook
ex.
```
const GetThemBars = (props) => {
...
const itemsRef = useRef(null);
const getMap = () => {
if (!itemsRef.current) {
// Initialize the Map on first usage.
itemsRef.current = new Map();
}
return itemsRef.current;
};
const focusOnBar = (id) => {
const map = getMap();
const node = map.get(id);
node.focus();
};
return (
<VictoryBar
...
// add event handler to call focusOnBar()
dataComponent={
<Bar
tabIndex={0} …
```
=> Added ability to forward refs in Bar and Path components

docs/src/content/introduction/index.md, docs/src/content/introduction/native.md, docs/src/styles/global.js
- Add links to React Native XL documentation in React Native sections
- https://victory-git-chore-victory-native-xl-links-formidable-labs.vercel.app/docs#getting-started-with-victory-native
- https://victory-git-chore-victory-native-xl-links-formidable-labs.vercel.app/docs/native
- Also added some styles for the markdown blockquote elements to differentiate them from regular paragraph text
#2693
=> Add links to React Native XL documentation in React Native sections

.changeset/warm-rocks-rest.md, packages/victory-legend/src/index.d.ts
Add missing 'size' property for the symbol in victory-legend 
https://github.com/FormidableLabs/victory/issues/2496
=> add missing size prop to symbol type in victory-legend

.changeset/tender-insects-rest.md, packages/victory-core/src/victory-util/textsize.ts
Fixes #2625
When React removes the measurement container SVG element from the DOM, label measurements result in `{ width: 0, height: 0 }`. This change verifies that the measurement container is still connected. If not, then a new measurement container is created.
=> Fix label measurement after SSR hydration mismatch

.changeset/clean-needles-grow.md, packages/victory-core/src/victory-primitives/circle.tsx, packages/victory-core/src/victory-primitives/clip-path.tsx, packages/victory-core/src/victory-primitives/line.tsx, packages/victory-core/src/victory-primitives/path.tsx, packages/victory-core/src/victory-primitives/rect.tsx, packages/victory-core/src/victory-primitives/text.tsx, packages/victory-core/src/victory-primitives/tspan.tsx, packages/victory-core/src/victory-util/user-props.ts
Fix the props passed to Victory Primitives by coercing the user supplied value functions into scaler values when neccessary and removing any conflicting props. 
This also solves a problem where Babel produces invalid tree shaking annotations for libraries like Rollup. (see #2692)
The following Typescript code
```
// @ts-expect-error FIXME: "id cannot be a number"
<circle vectorEffect="non-scaling-stroke" {...rest}>
<desc>{desc}</desc>
</circle>
```
Produces the following JS output in Babel
```
/*#__PURE__*/
// @ts-expect-error FIXME: "id cannot be a number"
React.createElement("circle", _extends({
vectorEffect: "non-scaling-stroke"
}, rest), /*#__PURE__*/React.createElement("desc", null, desc))
```
*BUG*: The problem with the above output is the TS comment between `/*#__PURE__*/` and the …
=> Correctly type props in Victory Primitives

.github/workflows/ci.yml, package.json
Improves the CI run time by running the 4 CI checks in parallel and only running specific Node versions for checks where that matters.
=> Use parallel builds in workflow for improved CI times

.changeset/seven-brooms-destroy.md, packages/victory-group/src/victory-group.tsx
Users are seeing a **maximum update depth exceeded** error when using the VictoryGroup component, specifically when trying to animate it #2708.
I was able to reproduce this in Storybook by rendering the following component:
```tsx
const Example = () => {
const [data, setData] = useState([]);
useEffect(() => {
setTimeout(() => {
setData([
{ x: 1, y: 2 },
{ x: 2, y: 3 },
{ x: 3, y: 5 },
{ x: 4, y: 4 },
{ x: 5, y: 7 },
]);
}, 2000);
}, []);
return (
<VictoryChart>
<VictoryGroup data={data} animate={{ duration: 1000 }}>
<VictoryBar />
<VictoryBar />
</VictoryGroup>
</VictoryChart>
);
};
```
When the component unmounts (tested in video by switching tab), the error appears.
https://github.com/FormidableLabs/victory/assets/9557798/f3e6b7e7-03c2-4ad9-a249-81cc5b428d35
The `initialProps` were …
=> Fix victory-group animation

.changeset/angry-pens-provide.md, packages/victory-chart/src/victory-chart.tsx, packages/victory-native/src/helpers/wrap-core-component.js, packages/victory-stack/src/victory-stack.tsx
Assign merged props to a const instead of modifying initialProps to avoid issues like https://github.com/FormidableLabs/victory/issues/2708 reoccurring
=> Assign merged props to a const instead of modifying initialProps

.changeset/spotty-apples-carry.md, packages/victory-polar-axis/src/helper-methods.ts, packages/victory-polar-axis/src/index.js, packages/victory-polar-axis/src/index.ts, packages/victory-polar-axis/src/types.ts, packages/victory-polar-axis/src/victory-polar-axis.tsx
Migrate polar axis to typescript
=> Migrate polar axis to typescript

.changeset/moody-mayflies-attack.md, packages/victory-core/src/victory-label/victory-label.tsx, stories/victory-label.stories.js
When using a user provided function for the `label` `dy` property, the component was not correctly calculating the new `y` offset based on the original position.
Added a new storybook use case so Chromatic can track this as well
Fixes #2715
=> Fix the label background position when using dy fns

packages/victory-area/src/area.tsx, packages/victory-area/src/helper-methods.tsx, packages/victory-axis/src/helper-methods.tsx, packages/victory-bar/src/bar.tsx, packages/victory-bar/src/helper-methods.ts, packages/victory-box-plot/src/helper-methods.tsx, packages/victory-candlestick/src/helper-methods.ts, packages/victory-chart/src/helper-methods.tsx, packages/victory-core/src/victory-label/victory-label.tsx, packages/victory-core/src/victory-primitives/arc.tsx, packages/victory-core/src/victory-primitives/background.tsx, packages/victory-core/src/victory-primitives/border.tsx, packages/victory-core/src/victory-primitives/line-segment.tsx, packages/victory-core/src/victory-primitives/point.tsx, packages/victory-core/src/victory-primitives/whisker.tsx, packages/victory-errorbar/src/error-bar.tsx, packages/victory-errorbar/src/helper-methods.tsx, packages/victory-group/src/helper-methods.tsx, packages/victory-histogram/src/helper-methods.ts, packages/victory-legend/src/helper-methods.ts, packages/victory-line/src/curve.tsx, packages/victory-line/src/helper-methods.ts, packages/victory-pie/src/helper-methods.js, packages/victory-pie/src/slice.js, packages/victory-polar-axis/src/helper-methods.ts, packages/victory-scatter/src/helper-methods.tsx, packages/victory-tooltip/src/flyout.js, packages/victory-voronoi/src/helper-methods.ts, packages/victory-voronoi/src/voronoi.js
There are a bunch of cases where we are reassigning component properties directly through the props (or equivalent) param. This PR ensures that props are assigned to a const rather than mutating the original object.
**Note:** There are _lots_ of cases where we're reassigning other, non-prop, params. Following this PR, I will create another which adds the [no-param-reassign](https://eslint.org/docs/latest/rules/no-param-reassign) eslint rule and refactors the remaining cases.
=> Refactor reassigned props

docs/README.md, docs/package.json, docs/yarn.lock
Update the docs site with the latest version and fix the Readme so its correct about how our deployments work. Also updates links to the new commerce.nearform.com URL.
=> Update site with latest version and nearform links

.changeset/large-cherries-rhyme.md, packages/victory-bar/src/bar.tsx, packages/victory-bar/src/path-helper-methods.ts, packages/victory-bar/src/victory-bar.tsx, packages/victory-canvas/src/canvas-bar.tsx, packages/victory-core/src/victory-util/common-props.tsx
- Fix the type signature of `getPath` in charts to match usage and documentation
- Add the missing `disableInlineStyles` prop in common components. This exists in documentation but was missing in the TS common props.
=> Fixes for incorrect chart props

.changeset/tough-spoons-float.md, packages/victory-shared-events/src/victory-shared-events.tsx
- Add missing defaultProps to VictorySharedEvents
- Regression caused by accidentally removing the defaultProps when migrating to TypeScript here https://github.com/FormidableLabs/victory/pull/2733/files#diff-069d2eda6414197c2671c7db2f0f632a42face6d114cbd71273a4dde2252a900L81-L83
Fixes #2751
=> Add missing defaultProps to VictorySharedEvents

packages/victory-core/src/victory-util/events.ts, stories/victory-area.stories.tsx, stories/victory-line.stories.tsx
Rename baseProps to newBaseProps and added new storybook testcases
=> 2753 victoryarea events not triggering fill in docs

.github/workflows/chromatic.yml
Chromatic requires a build to be run on main for proper ancestor control
https://www.chromatic.com/docs/branching-and-baselines/#what-if-i-skip-running-chromatic-on-a-base-branch
=> Ensure CI creates a chromatic baseline against main

.changeset/shiny-cows-bathe.md, packages/victory-area/src/victory-area.test.tsx, packages/victory-bar/src/victory-bar.test.tsx, packages/victory-candlestick/src/helper-methods.test.ts, packages/victory-candlestick/src/victory-candlestick.test.tsx, packages/victory-core/src/exports.test.ts, packages/victory-core/src/victory-util/axis.tsx, packages/victory-core/src/victory-util/data.test.tsx, packages/victory-core/src/victory-util/data.ts, packages/victory-core/src/victory-util/helpers.test.ts, packages/victory-core/src/victory-util/helpers.ts, packages/victory-core/src/victory-util/point-path-helpers.ts, packages/victory-errorbar/src/victory-errorbars.test.tsx, packages/victory-histogram/src/victory-histogram.test.tsx, packages/victory-line/src/victory-line.test.tsx, packages/victory-pie/src/victory-pie.test.tsx, packages/victory-scatter/src/victory-scatter.test.tsx, packages/victory-voronoi/src/victory-voronoi.test.tsx
Replace instances of `lodash.range` with equivalent native code. Includes tests built using comparisons to lodash as seen in the screenshot below.
Snapshot comparison
Relevant Code: https://github.com/FormidableLabs/victory/pull/2760/files#diff-40c5efad413c1e9989261214118a2c9e7d4de98b8b7b239f83778368f54e9991R220
Tests: https://github.com/FormidableLabs/victory/pull/2760/files#diff-1cf5b854b54e9f10213cc171a475a7d58b03f6006f4efdcb1eeba38811e0e8b6R206
=> Replace instances of lodash.range with native code

.changeset/pink-hats-count.md, docs/src/content/introduction/native.md, packages/victory-native/README.md, packages/victory-native/package.json, packages/victory/README.md
Use legacy npm dist-tag to avoid conflicts with victory-native-xl
This repository and victory-native-xl are both deploying to an npm package named `victory-native`. When they deploy the versions are conflicting under the `latest` tag.
Set this repo to deploy to the `legacy` tag.
=> Use legacy npm dist-tag to avoid conflicts with victory-native-xl

ISSUE_TEMPLATE.md, README.md
Updated the codesandbox example to be a TypeScript app, as well as make sure that all new sandboxes are created using the latest version of Victory
=> Update codesandbox example

stories/victory-tooltip.stories.tsx
Fix ts assertion error in victory-tooltip.stories.tsx -  can be seen failing here: https://github.com/FormidableLabs/victory/pull/2766
=> Fix ts assertion error in victory-tooltip.stories.tsx

docs/src/content/introduction/ssr.md
Add server side rendering documentation
=> add ssr documentation file

.github/workflows/ci.yml
Node 16.x is now deprecated due to the SSL security issue. Github will start disabling builds using Node 16.x before summer.
Previously, we ran a matrix of Node builds against multiple versions, but we are going to target a single version going forward since we are fully on Typescript and babel using build targets.
=> Remove node 16 from builds

.changeset/short-ads-hug.md, packages/victory-brush-container/src/victory-brush-container.tsx, packages/victory-cursor-container/src/victory-cursor-container.tsx, packages/victory-line/src/victory-line.tsx, packages/victory-native/src/components/victory-area.tsx, packages/victory-native/src/components/victory-axis.tsx, packages/victory-native/src/components/victory-bar.tsx, packages/victory-native/src/components/victory-boxplot.tsx, packages/victory-native/src/components/victory-brush-container.tsx, packages/victory-native/src/components/victory-brush-line.tsx, packages/victory-native/src/components/victory-candlestick.tsx, packages/victory-native/src/components/victory-chart.tsx, packages/victory-native/src/components/victory-cursor-container.tsx, packages/victory-native/src/components/victory-errorbar.tsx, packages/victory-native/src/components/victory-group.tsx, packages/victory-native/src/components/victory-histogram.tsx, packages/victory-native/src/components/victory-legend.tsx, packages/victory-native/src/components/victory-line.tsx, packages/victory-native/src/components/victory-pie.tsx, packages/victory-native/src/components/victory-polar-axis.tsx, packages/victory-native/src/components/victory-scatter.tsx, packages/victory-native/src/components/victory-selection-container.tsx, packages/victory-native/src/components/victory-stack.tsx, packages/victory-native/src/components/victory-voronoi-container.tsx, packages/victory-native/src/components/victory-voronoi.tsx, packages/victory-native/src/components/victory-zoom-container.tsx, packages/victory-native/src/helpers/wrap-core-component.tsx, packages/victory-selection-container/src/victory-selection-container.tsx, packages/victory-voronoi-container/src/victory-voronoi-container.tsx, packages/victory-zoom-container/src/victory-zoom-container.tsx
Relates to #2784
There were a couple of issues with the types in the `victory-native` package, caused by #2739.
Components that were wrapped with the `wrapCoreComponent` HOC were _only_ accepting props that were passed to the defaultProps object. For example:
```tsx
export const VictoryLine = wrapCoreComponent({
Component: VictoryLineBase,
defaultProps: {
width: Dimensions.get("window").width,
},
});
const Example = () => (
<VictoryLine
width={400} // ✅ exists in defaultProps
data={[]} // ❌ does not exist in defaultProps
/>
);
```
I have updated this by ensuring that the base component's props are passed as a generic to the `wrapCoreComponent` function:
```tsx
export const VictoryLine = wrapCoreComponent<VictoryLineProps>({
Component: VictoryLineBase,
defaultProps: {
width: …
```
=> Victory native type fixes

.changeset/eleven-geckos-trade.md, packages/victory-core/src/victory-animation/victory-animation.tsx
Convert victory-animation to function component
https://github.com/FormidableLabs/victory/assets/9557798/1f425984-3806-4741-ba2e-0e327538f760
https://github.com/FormidableLabs/victory/assets/9557798/7f80296c-9547-43ce-82e9-62b75c5c3a0e
=> Convert victory-animation to function component

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/question.yml
- Add config for issue templates so the template chooser shows up and does not allow blank submissions
- Fixes a bug with the `textarea` attributes
=> Add config for issue templates

.changeset/warm-pugs-hope.md, packages/victory-area/src/helper-methods.tsx, packages/victory-bar/src/bar-helper-methods.ts, packages/victory-bar/src/helper-methods.ts, packages/victory-box-plot/src/helper-methods.tsx, packages/victory-box-plot/src/victory-box-plot.tsx, packages/victory-candlestick/src/helper-methods.ts, packages/victory-candlestick/src/victory-candlestick.tsx, packages/victory-core/src/exports.test.ts, packages/victory-core/src/victory-util/add-events.tsx, packages/victory-core/src/victory-util/helpers.ts, packages/victory-errorbar/src/helper-methods.tsx, packages/victory-histogram/src/helper-methods.ts, packages/victory-legend/src/helper-methods.ts, packages/victory-line/src/helper-methods.ts, packages/victory-pie/src/helper-methods.ts, packages/victory-pie/src/victory-pie.tsx, packages/victory-scatter/src/helper-methods.tsx, packages/victory-voronoi/src/helper-methods.ts
Replace lodash isNil and isNan with native code.
Replaced with code directly from the lodash code base which is:
```
export function isNil(value: any): boolean {
return value == null;
}
```
The ES6 equivalent of lodash `isNan` is `Number.isNan`
=> Replace lodash isNil and isNan with native code

.changeset/weak-apes-clap.md, packages/victory-brush-container/src/brush-helpers.ts, packages/victory-brush-line/src/victory-brush-line.tsx, packages/victory-candlestick/src/candle.tsx, packages/victory-candlestick/src/helper-methods.ts, packages/victory-core/src/exports.test.ts, packages/victory-core/src/victory-container/victory-container.tsx, packages/victory-core/src/victory-transition/victory-transition.tsx, packages/victory-core/src/victory-util/add-events.tsx, packages/victory-core/src/victory-util/axis.tsx, packages/victory-core/src/victory-util/data.ts, packages/victory-core/src/victory-util/domain.ts, packages/victory-core/src/victory-util/events.ts, packages/victory-core/src/victory-util/helpers.ts, packages/victory-core/src/victory-util/scale.ts, packages/victory-core/src/victory-util/wrapper.tsx, packages/victory-create-container/src/create-container.ts, packages/victory-cursor-container/src/cursor-helpers.tsx, packages/victory-native/src/helpers/native-zoom-helpers.ts, packages/victory-pie/src/helper-methods.ts, packages/victory-pie/src/slice.tsx, packages/victory-selection-container/src/selection-helpers.tsx, packages/victory-shared-events/src/victory-shared-events.tsx, packages/victory-voronoi-container/src/victory-voronoi-container.tsx, packages/victory-voronoi-container/src/voronoi-helpers.ts, packages/victory-zoom-container/src/victory-zoom-container.tsx, packages/victory-zoom-container/src/zoom-helpers.ts
Replaces lodash `isFunction` with a native code function that acts as a Typescript type guard.
This is a stacked PR and is based on #2800. It will be rebased against main after #2800 is merged.
=> Replaces lodash isFunction with native code

.changeset/proud-islands-smoke.md, packages/victory-box-plot/src/victory-box-plot.tsx, packages/victory-core/src/victory-util/add-events.tsx, packages/victory-core/src/victory-util/axis.tsx, packages/victory-core/src/victory-util/data.ts, packages/victory-core/src/victory-util/domain.ts, packages/victory-core/src/victory-util/events.ts, packages/victory-core/src/victory-util/hooks/use-animation-state.ts, packages/victory-core/src/victory-util/scale.ts, packages/victory-core/src/victory-util/wrapper.tsx, packages/victory-create-container/src/create-container.ts, packages/victory-selection-container/src/selection-helpers.tsx, packages/victory-voronoi-container/src/voronoi-helpers.ts, packages/victory-voronoi/src/helper-methods.ts
Replace lodash array utils with native code
```
flatten => Array.flat()
some => Array.some()
without => Array.filter
last => array[array.length -1]
includes =>Array.includes
```
=> Replace lodash array utils with native code

.changeset/curvy-socks-sip.md, packages/victory-box-plot/src/helper-methods.tsx, packages/victory-core/src/victory-portal/portal.tsx, packages/victory-core/src/victory-util/add-events.tsx, packages/victory-core/src/victory-util/events.ts, packages/victory-core/src/victory-util/helpers.ts, packages/victory-core/src/victory-util/transitions.ts, packages/victory-legend/src/helper-methods.ts, packages/victory-shared-events/src/victory-shared-events.tsx, packages/victory-stack/src/helper-methods.tsx
Replace lodash keys with native code
Stacked PR from #2810
=> Replace lodash keys with native code

.github/workflows/issue-stale.yml, .github/workflows/issue-triage.yml
Add new workflows to help automate issue triage. Inspired by the Expo repository.
Any issues open longer than 90 days without activity will be labeled as "Stale". Any issue labeled "Stale" more than 7 days will be automatically closed with a message.
This bot automates the reply message to issues. When an issue does not contain enough information or sample code, simply label the issue as `Status: Needs More Info` and the bot will automatically post a message containing links and information for the issue author.
=> Add workflows to help automate issue triage

docs/src/content/common-props/common-props.md
It was pointed out in #2621 that VictoryBoxPlot doesn't support labelComponent. While we work on that enhancement and get feedback from the best way to move forward, I wanted to add a clarifying comment to the docs so that this information  might be found more easily for other users.
* Verified link works when running locally.
=> add note to labelComponent prop in commonprops

.changeset/rare-spies-agree.md, demo/ts/components/group-demo.tsx, packages/victory-core/src/victory-util/wrapper.tsx, packages/victory-group/src/helper-methods.tsx, stories/victory-box-plot.stories.tsx
VictoryGroup was overriding the styles of the child Boxplot with its wrapper styles. To fix this , new role check for `boxplot 
is added.
Fixes #1261
I tested this against the given code example in the issue and the style is now getting reflected.
=> Override VictoryGroup styles with VictoryBoxplot

.changeset/gorgeous-pianos-deliver.md, packages/victory-voronoi-container/src/voronoi-helpers.ts
Replace lodash isString with native equivalent.
Test output comparison
=> Replace lodash isString with native equivalent

.changeset/dry-peas-stare.md, packages/victory-core/src/victory-util/axis.tsx
Replace lodash identity with native code
=> Replace lodash identity with native code

.changeset/honest-camels-compete.md, packages/victory-core/src/exports.test.ts, packages/victory-core/src/victory-util/add-events.tsx, packages/victory-core/src/victory-util/collection.test.ts, packages/victory-core/src/victory-util/collection.tsx, packages/victory-shared-events/src/victory-shared-events.tsx
Replace lodash difference with native code
=> Replace lodash difference with native code

.github/actions/setup/action.yml, .github/workflows/issue-stale.yml, .github/workflows/issue-triage.yml
Upgrading our actions to remove node12 or node16 warnings.
~~actions/stale will likely still have a warning. To get to a version running on node20, there's some breaking changes that would affect what appears to be the desired behavior of our current stale action. Namely, in v7, the script no longer manages setting labels.~~
~~> Breaking Changes
In this release we prevent this action from managing the stale label on items included in exempt-issue-labels and exempt-pr-labels
We decided that this is outside of the scope of this action, and to be left up to the maintainer.~~
**_Edit: Hmm, on second thought I think I misinterpreted their message. I think it might be fine to upgrade to v9._**
**_Edit 2: I think we're fine to upgrade to v9 actually. I've done so.**
~~If we're ok with that, [I …
=> clear pipeline warnings

.changeset/stale-shirts-grow.md, packages/victory-area/src/victory-area.tsx, packages/victory-axis/src/victory-axis.tsx, packages/victory-bar/src/victory-bar.tsx, packages/victory-box-plot/src/victory-box-plot.tsx, packages/victory-brush-container/src/victory-brush-container.tsx, packages/victory-candlestick/src/victory-candlestick.tsx, packages/victory-create-container/src/create-container.ts, packages/victory-cursor-container/src/victory-cursor-container.tsx, packages/victory-errorbar/src/victory-errorbar.tsx, packages/victory-histogram/src/victory-histogram.tsx, packages/victory-legend/src/victory-legend.tsx, packages/victory-line/src/victory-line.tsx, packages/victory-native/src/components/victory-brush-container.tsx, packages/victory-native/src/components/victory-cursor-container.tsx, packages/victory-native/src/components/victory-selection-container.tsx, packages/victory-native/src/components/victory-tooltip.tsx, packages/victory-native/src/components/victory-voronoi-container.tsx, packages/victory-native/src/components/victory-zoom-container.tsx, packages/victory-pie/src/victory-pie.tsx, packages/victory-polar-axis/src/victory-polar-axis.tsx, packages/victory-scatter/src/victory-scatter.tsx, packages/victory-selection-container/src/victory-selection-container.tsx, packages/victory-tooltip/src/victory-tooltip.tsx, packages/victory-voronoi-container/src/victory-voronoi-container.tsx, packages/victory-voronoi/src/victory-voronoi.tsx, packages/victory-zoom-container/src/victory-zoom-container.tsx
Changes static fields that were defined as inline functions to avoid problems with some transpilers.
In components defined as classes, some static fields were defined as inline functions.
```
// source code
static getBaseProps = (props) => getBaseProps(props, fallbackProps);
// transpiled
static (0, $csb___helper_methods.getBaseProps) = props => (0, $csb___helper_methods.getBaseProps)(props, fallbackProps)
```
This PR changes those to plain functions in order to prevent a syntax error in transpilers that do not specify a default name for anonymous functions.
```
// source code
static getBaseProps(props){
return getBaseProps(props, fallbackProps);
}
// transpiled
static getBaseProps = function (props) {
return (0, $csb___helper_methods.getBaseProps)(props, fallbackProps);
};
```
Published …
=> Fix the signature of class static fields as functions

.changeset/lucky-roses-lick.md, packages/victory-area/src/area.tsx, packages/victory-bar/src/bar.tsx, packages/victory-candlestick/src/candle.tsx, packages/victory-chart/src/victory-chart.tsx, packages/victory-core/src/victory-label/victory-label.tsx, packages/victory-core/src/victory-primitives/arc.tsx, packages/victory-core/src/victory-primitives/background.tsx, packages/victory-core/src/victory-primitives/border.tsx, packages/victory-core/src/victory-primitives/line-segment.tsx, packages/victory-core/src/victory-primitives/point.tsx, packages/victory-core/src/victory-primitives/whisker.tsx, packages/victory-errorbar/src/error-bar.tsx, packages/victory-group/src/victory-group.tsx, packages/victory-line/src/curve.tsx, packages/victory-native/src/helpers/wrap-core-component.tsx, packages/victory-pie/src/slice.tsx, packages/victory-stack/src/victory-stack.tsx, packages/victory-tooltip/src/flyout.tsx, packages/victory-voronoi/src/voronoi.tsx
Ensure undefined props do not overwrite defaults
In previous updates, some functional components were changed to use the spread operator for assigning default values to component props. This inadvertently had the effect of preventing consumers from setting props to undefined.
```
// usage
<VictoryChart />
// final props
{ containerComponent: <VictoryContainer /> }
// usage
<VictoryChart containerComponent={undefined} />
// final props
{ containerComponent: undefined }
```
```
// usage
<VictoryChart />
// final props
{ containerComponent: <VictoryContainer /> }
// usage
<VictoryChart containerComponent={undefined} />
// final props
{ containerComponent: <VictoryContainer /> }
```
Fixes #2848
=> Ensure undefined props do not overwrite defaults

.changeset/honest-bananas-suffer.md, packages/victory-zoom-container/src/zoom-helpers.test.ts, packages/victory-zoom-container/src/zoom-helpers.ts
Fixes #2761
Bug fix
Verified manually and added unit tests with previously failing example (`"should't change the domain when zooming out with max zoom out with the cursor outside the container boundary"`).
With this simple solution if the cursor is outside the chart container it will be considered as if it is at the container edge.
Steps to reproduce the reproduce the unwanted behavior are reported in #2761.
The new behavior can be tested on the local ZoomContainerDemo example.
=> Fix zoom out of chart with cursor outside chart container

demo/ts/components/victory-legend-demo.tsx, demo/ts/components/victory-scatter-demo.tsx, docs/package.json, docs/src/content/docs/victory-legend.md, docs/src/content/docs/victory-scatter.md, docs/src/content/guides/custom-components.md, docs/src/partials/markdown/scope-map.js, package.json, pnpm-lock.yaml
Fixes # (issue) https://github.com/FormidableLabs/victory/issues/2892
This PR is a documentation update which provides examples to user on how to use `dataComponent` to pass custom icons to VictoryLegend and VictoryScatter.
=> update documentation to pass customIcons

.changeset/dry-games-press.md, packages/victory-voronoi-container/src/voronoi-helpers.ts
Fixes #2369
This issue seems present on many charts that work with mouse events e.g. https://github.com/FormidableLabs/victory/pull/1726. The fix over there was to reduce the throttling interval. That does alleviate the issue but doesn't eliminate it completely.
Note that there is an open PR here that also deals with the same issue: https://github.com/FormidableLabs/victory/pull/2890. I'm aware this PR exists, however I'm not sure that's the right change and I haven't seen any activity on it for weeks.
| Before | After |
|--------|--------|
| <video src="https://github.com/user-attachments/assets/33015f0b-dcb0-48e6-b2b6-d3b8bc3d09ab"/> |  <video src="https://github.com/user-attachments/assets/26c5e5d5-eba7-4ab3-b590-8baa93c5c987"/> | 
Verified manually by duplicating the chart shown in …
=> fix: cancel pending `onMouseMove` events when `onMouseLeave` is invoked

.changeset/soft-balloons-wink.md, packages/victory-core/src/victory-portal/victory-portal.tsx
Removes the use of `useId` to remain compatible with older versions of react
Fixes # https://github.com/FormidableLabs/victory/issues/2914
I tested this in a simple create-vite app with react 16. I also tested in a next app to make sure the ID generated doesn't break anything with SSR. It seems safe due to the component needing to be client rendered. I don't think any other randomness-related issues should be present.
=> Compatible unique id gen

.changeset/dry-books-invite.md, demo/ts/app.tsx, demo/ts/components/canvas-demo.tsx, demo/ts/components/events-demo.tsx, demo/ts/components/group-demo.tsx, demo/ts/components/horizontal-demo.tsx, demo/ts/components/immutable-demo.tsx, demo/ts/components/primitives-demo.tsx, demo/ts/components/stacked-theme-demo.tsx, demo/ts/components/victory-area-demo.tsx, demo/ts/components/victory-bar-demo.tsx, demo/ts/components/victory-box-plot-demo.tsx, demo/ts/components/victory-brush-container-demo.tsx, demo/ts/components/victory-chart-demo.tsx, demo/ts/components/victory-cursor-container-demo.tsx, demo/ts/components/victory-demo.tsx, demo/ts/components/victory-histogram-demo.tsx, demo/ts/components/victory-label-demo.tsx, demo/ts/components/victory-line-demo.tsx, demo/ts/components/victory-tooltip-demo.tsx, demo/ts/components/victory-voronoi-demo.tsx, packages/victory-core/src/victory-theme/clean.tsx, packages/victory-core/src/victory-theme/material.tsx
This PR adds a stack bar/area theme demo:
And also updates the following for the clean theme:
These demos have been manually checked on Chrome and Safari on MacOS.
=> Clean theme optimizations

demo/ts/app.tsx, demo/ts/components/theme-builder.tsx, demo/ts/components/theme-builder/config-preview.tsx, demo/ts/components/theme-builder/custom-options.tsx, demo/ts/components/theme-builder/index.tsx, demo/ts/components/theme-builder/theme-picker.tsx
This adds some basic functionality and layout updates for the theme builder app:
(Doesn't show the native color picker UI dropdown 🥲)
Tested on Chrome, desktop
=> feat: basic theme builder layout with qualitative scale customization

demo/ts/app.tsx, demo/ts/components/theme-builder.tsx, demo/ts/components/theme-builder/config-preview.tsx, demo/ts/components/theme-builder/custom-options.tsx, demo/ts/components/theme-builder/index.tsx, demo/ts/components/theme-builder/theme-picker.tsx, pnpm-lock.yaml
This PR refactors the demo app layout to be able to house the theme builder.
Tested on Chrome, desktop.
=> feat: update demo app layout

.changeset/four-melons-divide.md, packages/victory-core/src/victory-portal/victory-portal.tsx
Fixes # [(2928)](https://github.com/FormidableLabs/victory/issues/2928)
This PR makes sure generated id of portal does not change during it's lifetime.
I have forked victory and tested the change on my code which was affected by the bug.
=> fix: make sure VictoryPortal id does not change between re-renders

demo/ts/components/create-container-demo.tsx
Fixes `create-container-demo` passing an outdated prop, `selectedDomain` and it not being caught by TS. This was due to the `any` on the container as well as an implicit `any` on the demo's prop types. Removing this value instead of trying to map it to the new properties (like `zoomDomain`) has the fewest changes to the result.
Run demo locally
=> add types for create container, rm invalid prop

.changeset/wicked-fishes-flow.md, packages/victory-candlestick/src/victory-candlestick.test.tsx, packages/victory-candlestick/src/victory-candlestick.tsx
Adds a check for a boolean value in label text and does not return a label component if that is the case.
Fixes #2923
=> fix for 'Candlestick labels show incorrect midpoint label'

.changeset/proud-bugs-brush.md, demo/ts/components/victory-pie-demo.tsx, packages/victory-pie/src/helper-methods.ts, packages/victory-pie/src/victory-pie.test.tsx, stories/victory-pie.stories.tsx
Adds logic to sort pie chart slices by the categories in categories prop. Adds a story as well.
Fixes #2921
=> fix 'Pie Chart ignores categories prop'

.changeset/fuzzy-candles-rule.md, packages/victory-create-container/src/create-container.tsx
Updated types to allow for either prop types in generic or the `ContainerType` to be inferred. This helps types remain backwards compatible with older types https://github.com/eatyourpeas/victory/blob/9a20d57c111023867bbdf1a9f3b4835acd76f4d3/packages/victory-create-container/src/index.d.ts#L4
**NOTE** This isn't type safe. You can do
```
const VictoryZoomVoronoiContainer = createContainer<VictoryZoomContainerProps, VictoryBrushContainerProps>(
'zoom',
'voronoi',
);
``` 
and it won't complain. This was true in the older versions too since it was attempting to type JavaScript. Inferring the types is definitely the better option. To the point where **I am curious on if we should allow this behavior** 🤨
Fixes # https://github.com/FormidableLabs/victory/issues/2815
Tested locally with old …
=> backwards generic params compatibility

.changeset/quick-camels-cheer.md, packages/victory-area/src/victory-area.tsx, packages/victory-axis/src/victory-axis.tsx, packages/victory-bar/src/victory-bar.tsx, packages/victory-candlestick/src/victory-candlestick.tsx, packages/victory-core/src/victory-theme/types.ts, packages/victory-errorbar/src/victory-errorbar.tsx, packages/victory-group/src/victory-group.tsx, packages/victory-histogram/src/victory-histogram.tsx, packages/victory-line/src/victory-line.tsx, packages/victory-pie/src/victory-pie.tsx, packages/victory-polar-axis/src/types.ts, packages/victory-stack/src/victory-stack.tsx
Several components had props interface definitions with duplicate type definitions. These interfaces extend and underlying type and do not need to redefine the properties.
=> Remove duplicate types from interfaces

vercel.json, website/docs/api/victory-common-theme-props.mdx
The new Victory site was missing a redirect from the root `/docs` path to `/docs/introduction`.
The `VictoryCommonThemeProps` api document was incorrectly showing that it inherits from `VictoryCommonProps`.
=> Minor docs fixes

website/src/pages/_components/landing-featured-projects.tsx, website/src/pages/_components/landing-showcase.tsx
Fixes a couple Safari issues
Fixes https://github.com/FormidableLabs/victory/issues/2947
Localhost on Desktop Safari and simulator
| Before    | After |
| -------- | ------- |
| ![Screenshot 2024-11-05 at 11 04 29 AM](https://github.com/user-attachments/assets/60ac03af-2c30-4276-8fb1-c13ce2187bc8) | ![Screenshot 2024-11-05 at 11 07 48 AM](https://github.com/user-attachments/assets/1f977d6a-2d14-4e68-8c04-9f20e5ef0d76) |
| ![Screenshot 2024-11-05 at 11 05 35 AM](https://github.com/user-attachments/assets/ab30f88e-30c5-4e18-b241-b686526e0bf1) | ![Screenshot 2024-11-05 at 11 05 29 AM](https://github.com/user-attachments/assets/6b5aa07a-e702-4e1b-85b9-71f89954ad6d) |
=> safari tweaks

demo/ts/components/theme-builder/color-picker.tsx, demo/ts/components/theme-builder/color-scale-options.tsx, demo/ts/components/theme-builder/config-mapper.tsx, demo/ts/components/theme-builder/index.tsx, demo/ts/components/theme-builder/options-config.ts, demo/ts/components/theme-builder/slider.tsx, demo/ts/components/theme-builder/utils.ts
This PR adds data and label option controls for area charts in the Victory theme builder app.
Fixes # (issue)
Tested on chrome desktop.
=> feat: add area chart options to theme builder

website/docs/charts/candlestick.mdx
This documentation update adds a brush and zoom live code example to the Candlestick chart
https://github.com/user-attachments/assets/64735442-8ae3-46a5-a731-7a0db2e0c74f
- Documentation update
=> Docs: Add Brush and Zoom sample to Candlestick chart

website/src/pages/themes/_components/accordion.tsx, website/src/pages/themes/_components/code-block.tsx, website/src/pages/themes/_components/color-picker.tsx, website/src/pages/themes/_components/color-scale-options.tsx, website/src/pages/themes/_components/config-mapper.tsx, website/src/pages/themes/_components/config-preview.tsx, website/src/pages/themes/_components/control.tsx, website/src/pages/themes/_components/select.tsx, website/src/pages/themes/_components/slider.tsx, website/src/pages/themes/_config.tsx, website/src/pages/themes/_utils.ts, website/src/pages/themes/index.tsx
This PR adds the ability to override color scales on a chart by chart basis and also adds some final polish for theme builder MVP ✨
=> feat: add color scale overrides and final polish

website/src/pages/themes/_components/color-scale-options.tsx, website/src/pages/themes/_config.tsx, website/src/pages/themes/index.tsx
This PR adds some missing color palettes to theme builders and allows for a default color palette.
=> Feat: theme builder palette fixes

.storybook/main.ts
Fixes the following error when running pnpm storybook:dev locally:
```
SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: @storybook/react-webpack5/preset.
```
Reference: https://storybook.js.org/docs/faq#how-do-i-fix-module-resolution-in-special-environments
Fixes error by resolving storybook addons using absolute paths as [recommended by the docs](https://storybook.js.org/docs/faq#how-do-i-fix-module-resolution-in-special-environments)
Fixes #2993 
Run `pnpm storybook:dev` locally  and verify storybook opens successfully.
=> Fix running storybook:dev locally

.changeset/four-lies-rush.md, package.json, packages/victory-area/src/helper-methods.tsx, packages/victory-core/src/victory-util/axis.tsx, packages/victory-core/src/victory-util/domain.ts, packages/victory-core/src/victory-util/helpers.ts, packages/victory-core/src/victory-util/user-props.ts, pnpm-lock.yaml
Upgrade typescript to 5.7.2 and correct any Type errors.
Diff results of the output file show only the expected changes
=> Upgrade typescript to 5.7.2

.changeset/poor-crabs-hear.md, packages/victory-axis/src/helper-methods.tsx, packages/victory-chart/src/helper-methods.tsx, packages/victory-core/src/victory-clip-container/victory-clip-container.tsx, packages/victory-core/src/victory-label/victory-label.tsx, packages/victory-core/src/victory-util/helpers.test.ts, packages/victory-core/src/victory-util/helpers.ts, packages/victory-core/src/victory-util/type-helpers.ts, packages/victory-cursor-container/src/victory-cursor-container.tsx, packages/victory-group/src/helper-methods.tsx, packages/victory-legend/src/helper-methods.ts, packages/victory-pie/src/helper-methods.ts, packages/victory-polar-axis/src/helper-methods.ts, packages/victory-scatter/src/helper-methods.tsx, packages/victory-stack/src/helper-methods.tsx, packages/victory-tooltip/src/victory-tooltip.tsx, packages/victory-voronoi-container/src/victory-voronoi-container.tsx, packages/victory-voronoi-container/src/voronoi-helpers.ts
Update types in victory-core helpers to improve refactoring and static type checking
- Removed an unused function from `type-helpers.ts`
- [Updated `getPoint`](https://github.com/FormidableLabs/victory/pull/2999/files#diff-40c5efad413c1e9989261214118a2c9e7d4de98b8b7b239f83778368f54e9991R116) to use coalesce
- Removed the [string type property selection](https://github.com/FormidableLabs/victory/pull/2999/files#diff-40c5efad413c1e9989261214118a2c9e7d4de98b8b7b239f83778368f54e9991R158) from `getPadding`
- Updated all usages of `getPadding`
=> Improve types in victory-core helpers

.changeset/orange-rockets-rest.md, packages/victory-cursor-container/src/victory-cursor-container.tsx
Correct the rendering regression caused by the change in #2999 and captured by Chromatic in https://www.chromatic.com/test?appId=5b4acf7c54c0490024d5980b&id=675360427f60e8728902e703 that caused the cursor to render outside the boundaries of the chart
=> Fix regression in cursor rendering caused by #2999

website/src/pages/themes/_components/base-theme-panel.tsx, website/src/pages/themes/_components/chart-panel.tsx, website/src/pages/themes/_components/options-panel.tsx, website/src/pages/themes/_components/sidenav.tsx, website/src/pages/themes/_config/axis.tsx, website/src/pages/themes/_config/chart.tsx, website/src/pages/themes/_config/index.tsx, website/src/pages/themes/_providers/themeProvider.tsx, website/src/pages/themes/index.tsx
This PR refactors `ChartPanel` to be more generic, which allows it to be used for the axis panel as well. I also updated theme builder to have the `clean` theme auto-selected as the base theme when the app loads.
=> Feat: theme builder refactor axis panel

.changeset/large-comics-repeat.md, packages/victory-bar/src/helper-methods.ts, packages/victory-bar/src/victory-bar.tsx
This fixes a VictoryBar issue related to #2970. That change causes a "props.groupComponent is undefined" error in our VictoryBar wrapper.
Fixes #3013
Tested changes locally with our Victory-bar wrapper to ensure error is no longer generated.
=> "props.groupComponent is undefined" error

website/src/pages/themes/_components/button.tsx, website/src/pages/themes/_components/checkbox.tsx, website/src/pages/themes/_components/color-picker.tsx, website/src/pages/themes/_components/color-scale-override-selector.tsx, website/src/pages/themes/_components/export-panel.tsx
This PR adds functionality that allows the user to choose which theme options to include in their export in theme builder.
=> feat(theme-builder): allow users to choose which options to include in theme export

website/src/pages/themes/_components/control.tsx, website/src/pages/themes/_components/slider.tsx, website/src/pages/themes/_components/toggle.tsx
This PR fixes the issue where sliders were going between controlled/uncontrolled states when the config value for the slider is `undefined`.
=> Feat: theme builder default slider

website/docs/api/victory-container-props.mdx, website/docs/api/victory-voronoi-container.mdx
Fixes a couple extra `}` characters in `victory-voronoi-container.mdx` and `victory-container-props.mdx`
Ran docs locally, verified change
=> Fix typo in docs

website/src/pages/themes/_components/color-palette-selector.tsx, website/src/pages/themes/_components/color-picker-list.tsx, website/src/pages/themes/_components/color-picker.tsx, website/src/pages/themes/_components/color-scale-override-selector.tsx, website/src/pages/themes/_components/control.tsx, website/src/pages/themes/_config/index.tsx, website/src/pages/themes/_config/palette.tsx
This PR simplifies the color picker UI and also adds the ability to add and remove colors from a palette.
https://www.notion.so/nearform/Simplify-color-picker-1759aa50dea2800eb152e80015f77385?pvs=4
| Color Scale | Individual Color Picker |
| --- | --- |
| ![2025-01-09 13 53 41](https://github.com/user-attachments/assets/8ccf47b5-7636-450f-a9b1-0f85faf4a8cc) | ![2025-01-09 13 55 36](https://github.com/user-attachments/assets/cc72d752-1c26-4eed-b7c0-93c5360ff12e) |
=> feat(theme-builder): simplify color picker

website/src/pages/themes/_components/color-scale-override-selector.tsx, website/src/pages/themes/_components/toggle.tsx
This PR improves accessibility around the toggle component and fixes the issue where the user is unable to tab-focus the toggle.
https://www.notion.so/nearform/Toggle-focus-state-missing-1759aa50dea2807b8a0ecfa747b6ec7a?pvs=4
=> feat(theme-builder): improve toggle accessibility

website/src/hooks/useLocalStorage.tsx, website/src/pages/themes/_providers/themeProvider.tsx
This PR stores the selected base theme and custom theme config in local storage. That way, if users navigate away, their work is saved.
Relates to https://www.notion.so/nearform/Display-prompt-when-navigating-away-mid-edit-1759aa50dea280358b9ef7f65bb45dcb?pvs=4
=> feat(theme-builder): keep config in local storage

website/src/pages/themes/_components/chart-panel.tsx
This PR sets a default chart and axis type for when users first navigate to those options panels to avoid having an empty state in the preview area.
https://www.notion.so/nearform/Add-simple-empty-state-1759aa50dea280008e82e4ecc9b35e03?pvs=4
=> feat(theme-builder): default chart + axis type

.changeset/fifty-pears-brake.md, demo/rn/package.json, demo/rn/src/screens/chart-screen.tsx, packages/victory-native/README.md, packages/victory-native/src/components/victory-zoom-container.tsx, pnpm-lock.yaml
Fixes #3022 
Previously, victory-native/victory-zoom-container spread the result of `useVictoryZoomContainer` into `VictoryContainer`
```ts
const props = useVictoryZoomContainer(...)
return <VictoryContainer {...props} />;
```
Where the return type of `useVictoryZoomContainer` is
```ts
{
props: VictoryZoomContainerMutatedProps;
children: React.ReactElement[];
}
```
Because `VictoryContainer` received the entire `props` object as a prop, instead of spreading its properties, values such as `width` and `height` were `undefined` - leading to the svg element to render with undefined values in its `viewBox`, e.g.
```html
<svg viewBox="0 0 undefined undefined" ...>
```
thus clipping the rendered chart.
Destructure the props/children result from `useVictoryContainer` and pass correctly to …
=> Fix victory-native/victory-zoom-container clipping bug

website/docs/guides/localization.mdx
Adds comprehensive documentation for Victory chart localization. The guide includes:
- Date and number formatting using Intl APIs
- RTL text direction support for languages like Arabic
- Custom formatting for labels and tooltips
Closes #3034
I ran the docs locally and verified changes
=> added guide for Victory chart localization in docs

website/src/css/custom.css, website/src/pages/themes/_components/accordion.tsx, website/src/pages/themes/_components/chart-panel.tsx, website/src/pages/themes/_components/code-panel.tsx, website/src/pages/themes/_components/color-picker-list.tsx, website/src/pages/themes/_components/color-picker.tsx, website/src/pages/themes/_components/color-scale-override-selector.tsx, website/src/pages/themes/_components/control.tsx, website/src/pages/themes/_components/main.tsx, website/src/pages/themes/_components/panel-header.tsx, website/src/pages/themes/_components/select.tsx, website/src/pages/themes/_components/sideNavButton.tsx, website/src/pages/themes/_components/slider.tsx, website/src/pages/themes/_components/theme-preview/options.tsx, website/src/pages/themes/_components/toggle.tsx, website/src/pages/themes/index.tsx, website/tailwind.config.ts
This PR updates styles for components used in the options panel to match the new design files. ([Notion](https://www.notion.so/nearform/Toggle-label-styling-revision-1759aa50dea280809e79c2ec4ff0196f?pvs=4),  [Figma](https://www.figma.com/design/TmM8v8Xvr77HYVqYzyE3Mb/Victory-Theme-Builder?node-id=354-923&t=SYzG2CmgwpLe4fTj-0))
=> feat(theme-builder): update options components styles

website/docs/api/victory-area.mdx, website/docs/api/victory-theme.mdx, website/docs/guides/themes.mdx, website/docusaurus.config.ts, website/src/pages/themes/_components/color-scale-override-selector.tsx, website/src/pages/themes/_components/control.tsx, website/src/pages/themes/_components/slider.tsx, website/src/pages/themes/_config/global.tsx, website/src/pages/themes/_config/index.tsx, website/src/pages/themes/_utils.ts
This PR updates docs and fixes the last of the soft launch blocking bugs.
Tasks:
- [Update theme and styling docs](https://www.notion.so/nearform/Update-theme-and-styling-docs-1899aa50dea28001bc84f9ef3cdbacc3?pvs=4)
- [Disable dark mode](https://www.notion.so/nearform/Disable-dark-mode-1889aa50dea28066bffdf0f86b57de3c?pvs=4)
- [Update global options min + max values to prevent crashes](https://www.notion.so/nearform/Update-global-options-min-max-values-to-prevent-crashes-1889aa50dea28059b915cd0ef7a4575b?pvs=4)
- [Prevent colors from disappearing from default color scales when enabling/disabling custom colors](https://www.notion.so/nearform/Prevent-colors-from-disappearing-from-default-color-scales-when-enabling-disabling-custom-colors-1889aa50dea2807a8c14f065b9c893fb?pvs=4)
- [Add ability …
=> docs(theme-builder): update docs and launch-blocking bug fixes
